// tag::FEEDBACK[]
:filename: 01-module-block-1/LZ-1-02.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-1-2]]
==== LZ 1-2: Dies ist das erste Lernziel, in Kategorie xy
- Was sollen die Teilnehmer können?
   * Fähigkeit 1
   * Fähigkeit 2
   * Fähigkeit 3
   * etc.

- Was sollen die Teilnehmer verstehen?
  * Aussage 1
  * Behauptung 2
  * Erfahrung 3
  * Zusammenhang 4
  * etc.
- Was sollen die Teilnehmer kennen?
  * Zusammenhang Nr. 1
  * Norm Nr. 2
  * Buch Nr. 3
  * etc.

// end::DE[]

// tag::EN[]
[[LG-1-2]]
==== LG 1-2: Know and explain typical categories of problems in software (R1)

* Conceptual weaknesses, e. g., violation of conceptual integrity, redundancy, use of inappropriate technology, incorrect use of technology.
* Structural problems in data or data structures.
* Structural problems in source code, such as:
* Missing or inadequate modularisation,
* Tight coupling,
* High complexity,
* Low cohesion,
* Flaws in programming, e. g., non-idiomatic use of languages or tools.
* Runtime problems in systems, like instability, lack of robustness or reliability, insufficient performance or extensive resource demands, insufficient scalability, insufficient transparency of system processes
* “Legacy” gathered by frequent changes of requirements made under time and/or cost pressure.
* Recognize and name different kinds of technical debts.
* Problems to achieve quality goals or requirements, e. g., insufficient changeability or maintainability, low flexibility, insufficient security or lack of portability.
* Problems in development, operations or other involved processes (e. g., requirements management, test/QA, configuration, deployment, monitoring/alerting).

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
