
// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Dies ist das erste Lernziel, in Kategorie xy
- Was sollen die Teilnehmer können?
   * Fähigkeit 1
   * Fähigkeit 2
   * Fähigkeit 3
   * etc.

- Was sollen die Teilnehmer verstehen?
  * Aussage 1
  * Behauptung 2
  * Erfahrung 3
  * Zusammenhang 4
  * etc.
- Was sollen die Teilnehmer kennen?
  * Zusammenhang Nr. 1
  * Norm Nr. 2
  * Buch Nr. 3
  * etc.

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Know and explain reasons for software changes (R1)

* Extending and changing features
* Change in quality requirements and goals
* Changes in technical or business context (e. g., change in external interfaces)
* Bug fixing
* Changes in organisation (e. g., changes of legal conditions or requirements; organisational structure of business units, development or operations)
* Reduce of costs or efforts, especially with respect to:
* Costs or efforts of development
* Costs or efforts of operations
* Costs of bug fixing and consequential damage
* Costs of involved processes
* Opportunity costs
* Intrinsic motivation of stakeholders, especially software developers and architects.
* Update of applied technology such as operating systems, middleware, libraries, frameworks, hardware or similar.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
