= Curriculum for the CPSA-advanced module IMPROVE

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status 
image:https://travis-ci.org/isaqb-org/curriculum-improve.svg?branch=master["Build Status", link="https://travis-ci.org/isaqb-org/curriculum-improve"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-improve/master.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-improve.svg["Contributors",link="https://github.com/isaqb-org/curriculum-improve/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-improve.svg["Issues",link="https://github.com/isaqb-org/curriculum-improve/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-improve.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-improve/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the curriculum for the iSAQB Advanced Level "IMPROVE" written in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to use this template

1. Clone or download - but include the submodule:
+
--
[source,shell]
----
git clone git@github.com/isaqb-org/curriculum-improve.git --recursive
----
--
2. Build it with gradle via `./gradle`.
3. Look into the file `build.gradle` to see what attributes you may configure. Watch for:
** the `language` attribute, either `DE` (German) or `EN` (English);
** the output formats called `backends` (pdf and/or html5);
** the document version.

== How to write iSAQB Advanced Level Curricula with AsciiDoc

Please take a look at https://github.com/isaqb-org/advanced-template#how-to-write-isaqb-advanced-level-curricula-with-asciidoc


== Maintainers

This repository is currently maintained by Gernot Starke, Markus Harrer and Benjamin Wolf.
It was forked from https://github.com/isaqb-org/advanced-template, so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::LICENSE.adoc[]
