= https://isaqb.org[iSAQB] Curriculum for the CPSA-advanced Module IMPROVE
:toc:
:toclevels: 3
:toc-title: Table of Contents

== Content
This repository contains the AsciiDoc sources of the curriculum for the iSAQB Advanced Level "IMPROVE".

This is <<copyrighted,copyrighted work>>.


== Status
image:https://github.com/isaqb-org/curriculum-improve/actions/workflows/build_main.yml/badge.svg["CI/Release"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-improve/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-improve.svg["Contributors",link="https://github.com/isaqb-org/curriculum-improve/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-improve.svg["Issues",link="https://github.com/isaqb-org/curriculum-improve/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-improve.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-improve/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


=== Version history

(summarizing changes, although no release was published between 2019 and 2025)

[cols="1,1,5"]
|===
| Version | Date | Comments

| 2025.1  | 2025 | Major refinement of Learning Goals (LGs), revising content (improvement strategy, tech debt, databases, metrics). >80 commits.
| | 2024  | A significant German version was added. LGs were enhanced to focus on management support and funding. More time was allocated to "estimate and assess" chapters. About 60 commits.
| | 2020-2023 | Support for internationalization (i18n) and translations. Some learning goals were merged. First German content. In total, about 150 commits. 
| 1.6.1-EN  | 2019 | first release, English only
|===


For open, closed and in-progress-issues: see our https://github.com/orgs/isaqb-org/projects/4[Kanban-Board]

== How to contribute or participate
Create an issue, a merge- or pull-request.


== How to build

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-improve.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-improve.git --recursive
----
--

. Build it with gradle via `./gradle-tools/gradlew buildDocs`.
. Look into the file `build.gradle` to see what attributes you may configure. Watch for:
** the `language` attribute, either `DE` (German) or `EN` (English);
** the output formats called `backends` (pdf and/or html5);
** the document version.


== How to contribute or participate
Create an issue, a merge- or pull-request here!

For open, closed and in-progress-issues: see our https://github.com/orgs/isaqb-org/projects/4[Kanban-Board]

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Gernot Starke, Markus Harrer, and Benjamin Wolf.
It was forked from https://github.com/isaqb-org/advanced-template, so the contributors of that project basically contributed to this one, too.


== More Contributors

Parts of the content origined from the https://aim42.org[aim42 open source method] for architecture improvement. Thanx to all https://github.com/aim42/aim42/graphs/contributors[contributors] of aim42!



[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
