=== {learning-goals}

// tag::DE[]
[[LZ-2-1]]
==== LZ 2-1: Grundlagen der Analyse zur Trennung von „Problem“ und „Lösung“

* Problemanalyse begrifflich von Problemlösung trennen
* Problem und Lösungsansatz in m:n Verhältnis einander zuordnen
* Komplexe Probleme in Teilprobleme zerlegen


[[LZ-2-2]]
==== LZ 2-2: Typische Praktiken und Methoden zur Ist-Analyse

Typische Praktiken der Ist-Analyse kennen und für die jeweilige Situation, das Budget, die Zeit bzw. die Beteiligten angemessene auswählen können. Dazu gehören insbesondere folgende Ansätze:

* Stakeholder-Analyse und -interview
* Kontextanalyse
* Qualitative Analyse (etwa ATAM), insbesondere die Analyse von Qualitätszielen
* Analyse von strukturellen Abweichungen zwischen Soll- und Ist-Architektur
** Quantitative Analysemethoden und -praktiken, etwa:
** Code-Metriken (Größenmaße, Kopplung, Komplexität, Kohäsion)
** Organisatorische Metriken wie Kosten, Zeit und Anzahl. Beispiele: Fehleranzahl und Fehlerraten, Entwicklungsgeschwindigkeit, Kosten pro Feature, Kosten pro behobenem Fehler etc.
** Laufzeitmetriken, wie Zeit- und Ressourcenbedarf  und Werkzeuge zu deren Erhebung
* Analyse von Anwendungsdaten: Untersuchung von Datenstrukturen und -inhalten
* Dokumentationsanalyse
* Analyse der technischen Umgebung (Laufzeit- und Betriebsumgebung: Hardware, Betriebsumgebung, Netzwerke, beteiligte Betriebssysteme und Infrastruktursoftware)
* Analyse von Entwicklungsprozessen (Anforderungsmanagement, Entwurf/Implementierung, Test/Qualitätssicherung sowie Übergabe an Betrieb/Produktion)
* Analyse von Betriebsprozessen
* Analyse weiterer Prozesse und Aufgaben, die Probleme für Entwicklung und Änderung von Systemen beeinflussen können, beispielsweise Management, Budgetierung, Support, Governance, Outsourcing/Offshoring, Lieferantenmanagement u. a.

[[LZ-2-3]]
==== LZ 2-3: Gefundene Probleme und Risiken methodisch dokumentieren

* Teilnehmer sollen in der Lage sein, im Rahmen von Verbesserungs- und Veränderungsprozessen eine angemessene Dokumentation gefundener Probleme (Issues) und Risiken aufzusetzen
* Werkzeuge und Beispiele für Problemdokumentation

[[LZ-2-4]]
==== LZ 2-4: Stakeholderanalyse und -interviews

* Stakeholderanalyse zur Identifikation der wesentlichen beteiligten Personen sowie deren Rollen und Intentionen planen, durchführen und dokumentieren
* Methodiken zur Konzeption und Durchführung von Stakeholder-Interviews kennen
* Vorbereitende Fragebögen erstellen können
* Situativ im Verlauf von Interviews spezifisch auf sich ergebende neue Sachverhalte eingehen und diese in die Analyse einbeziehen

[[LZ-2-5]]
==== LZ 2-5: Kontextanalyse
* Kontextabgrenzung durchführen und dokumentieren: Systeme bezüglich ihrer fachlichen und technischen Nachbarn abgrenzen und dabei externe Schnittstellen identifizieren.
* Zusammenhänge zwischen externen Schnittstellen und möglichen Stakeholdern erkennen und für Problemanalyse ausnutzen können.
* Probleme und Risiken externer Schnittstellen erarbeiten (u. a. über Interviews, Analyse bekannter Fehler, Laufzeitanalyse, Protokoll- oder Loganalyse, Analyse der organisatorischen Beziehungen, Analyse der Qualitätsmerkmale und/oder Service-Levels).

[[LZ-2-6]]
==== LZ 2-6: Code- und Strukturanalyse
(Statische) Analyse von bestehendem Quellcode und dessen Strukturen durchführen und dokumentieren.
(Hierzu können in der Schulung entsprechende Werkzeuge eingesetzt werden, sind jedoch nicht Voraussetzung).

[[LZ-2-7]]
==== LZ 2-7: Grundlegende Laufzeitanalysen
(Dynamische) Analyse von bestehenden Systemen planen und durchführen können, beispielsweise hinsichtlich Laufzeiten, Ressourcen-Bedarf, Lastverhalten. (Hierzu können in der Schulung Werkzeuge eingesetzt werden, sind jedoch nicht Voraussetzung).

// end::DE[]

// tag::EN[]
[[LG-2-1]]
==== LG 2-1: Basics of the analysis to distinguish “problem” from “solution”

* Distinguish between “analyzing problems” and “solving problems”
* Form m:n relation between problems and solution approaches
* Decomposition of complex problems

[[LG-2-2]]
==== LG 2-2: Typical practices and methods for current state analysis

Know typical practices for current state analysis and being able to
choose the appropriate method in each situation according to budget,
time or the involved stakeholders. This includes approaches such as:

* Stakeholder analysis and interview
* Contextual analysis
* Qualitative analysis (e.g., ATAM), in particular, analysis of quality goals
* Analysis of structural deviations between target and current architecture
* Quantitative analysis methods and practices, such as:
** Code metrics (size metrics, coupling, complexity, cohesion)
** Organizational metrics, such as costs, time, and countable items. Example: error counts and failure rates, development speed, cost per feature, cost per fixed bug, etc.
** Runtime metrics, e.g., time and resource demands as well as tools to measure these metrics
* Application data analysis: examination of data structures and contents
* Documentation analysis
* Analysis of technical environment (runtime and operations: hardware, operations environment, networks, operating systems involved, and infrastructure software)
* Analysis of development processes (requirements engineering, design/implementation, test/QA, and handover to operations)
* Analysis of operation processes
* Analysis of further processes and tasks that may influence development problems and system changes, e.g., management, budgeting, support, governance, outsourcing/offshoring, procurement.

[[LG-2-3]]
==== LG 2-3: Methodically document identified problems and risks

* Participants shall be able to initiate adequate documentation of problems (issues) and risks that have been identified by an improvement- and change process.
* Tools and examples for documenting problems.

[[LG-2-4]]
==== LG 2-4: Stakeholder analysis and interviews

* Plan, perform, and document a stakeholder analysis to identify essential people involved, their roles, and intents.
* Know methods to structure and execute stakeholder interviews.
* Being able to create preparatory questionnaires.
* React flexibly to new relevant information obtained during interviews; incorporate these in the analysis.

[[LG-2-5]]
==== LG 2-5: Context analysis

* Define and document contextual boundaries: demarcate systems with respect to their technically and logically related neighbors, identify external interfaces.
* Identify connections between external interfaces and stakeholders and use this information for problem analysis.
* Elaborate problems and risks of external interfaces (e.g., with interviews, analysis of known failures, runtime analysis, protocol or log analysis, analysis of organizational dependencies, analysis of quality attributes and/or service levels).

[[LG-2-6]]
==== LG 2-6: Code and structural analysis

* Perform and document (static) analysis of existing source code and its structure.
(For this purpose, tools may be used in the training. However, these are not a prerequisite).

[[LG-2-7]]
==== LG 2-7: Runtime analysis

Plan and perform (dynamic) analysis of existing systems, e.g., with respect to runtime behavior, resource utilization, load response.
(For this purpose, tools may be used in the training. However, these are not a prerequisite).

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
