// tag::DE[]
[[LZ-2-2]]
==== LZ 2-2: Typische Praktiken und Methoden zur Ist-Analyse

Typische Praktiken der Ist-Analyse kennen und für die jeweilige Situation, das Budget, die Zeit bzw. die Beteiligten angemessene auswählen können. Dazu gehören insbesondere folgende Ansätze:

* Stakeholder-Analyse und -interview
* Kontextanalyse 
* Qualitative Analyse (etwa ATAM), insbesondere die Analyse von Qualitätszielen 
* Analyse von strukturellen Abweichungen zwischen Soll- und Ist-Architektur
** Quantitative Analysemethoden und -praktiken, etwa:
** Code-Metriken (Größenmaße, Kopplung, Komplexität, Kohäsion) 
** Organisatorische Metriken wie Kosten, Zeit und Anzahl. Beispiele: Fehleranzahl und Fehlerraten, Entwicklungsgeschwindigkeit, Kosten pro Feature, Kosten pro behobenem Fehler etc. 
** Laufzeitmetriken, wie Zeit- und Ressourcenbedarf  und Werkzeuge zu deren Erhebung 
* Analyse von Anwendungsdaten: Untersuchung von Datenstrukturen und -inhalten 
* Dokumentationsanalyse
* Analyse der technischen Umgebung (Laufzeit- und Betriebsumgebung: Hardware, Betriebsumgebung, Netzwerke, beteiligte Betriebssysteme und Infrastruktursoftware)
* Analyse von Entwicklungsprozessen (Anforderungsmanagement, Entwurf/Implementierung, Test/Qualitätssicherung sowie Übergabe an Betrieb/Produktion)
* Analyse von Betriebsprozessen
* Analyse weiterer Prozesse und Aufgaben, die Probleme für Entwicklung und Änderung von Systemen beeinflussen können, beispielsweise Management, Budgetierung, Support, Governance, Outsourcing/Offshoring, Lieferantenmanagement u. a. 

// end::DE[]

// tag::EN[]
[[LG-2-2]]
==== LG 2-2: Typical practices and methods for current state analysis

Know typical practices for current state analysis and being able to
choose the appropriate method in each situation according to budget,
time or the involved stakeholders. This includes approaches such as:

* Stakeholder analysis and interview,
* Contextual analysis,
* Qualitative analysis (e. g., ATAM), in particular, analysis of quality goals,
* Analysis of structural deviations between target and current architecture,
* Quantitative analysis methods and practices, such as:
* Code metrics (size metrics, coupling, complexity, cohesion),
* Organisational metrics, such as costs, time, and countable items. Example: error counts and failure rates, development speed, cost per feature, cost per fixed bug, etc.,
* Runtime metrics, e. g., time and resource demands as well as tools to measure these metrics.
* Data analysis: examination of data structures and contents,
* Documentation analysis,
* Analysis of technical environment (runtime and operations: hardware, operations environment, networks, operating systems involved and infrastructure software)
* Analysis of development processes (requirements engineering, design/implementation, test/QA and handover to operations)
* Analysis of operation processes
* Analysis of further processes and tasks that may influence development problems and system changes, e. g.,: management, budgeting, support, governance, outsourcing/offshoring, procurement.

// end::EN[]
