// tag::FEEDBACK[]
:filename: 02-module-block-2/LZ-2-02.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-2-2]]
==== LZ 2-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.
// end::DE[]

// tag::EN[]
[[LG-2-2]]
==== LG 2-2: Know typical practices and methods for current state analysis and being able to apply them (R1)

Know typical practices for current state analysis and being able to
choose the appropriate method in each situation according to budget,
time or the involved stakeholders. This includes approaches such as:

* Stakeholder analysis and interview,
* Contextual analysis,
* Qualitative analysis (e. g., ATAM), in particular, analysis of quality goals,
* Analysis of structural deviations between target and current architecture,
* Quantitative analysis methods and practices, such as:
* Code metrics (size metrics, coupling, complexity, cohesion),
* Organisational metrics, such as costs, time, and countable items. Example: error counts and failure rates, development speed, cost per feature, cost per fixed bug, etc.,
* Runtime metrics, e. g., time and resource demands as well as tools to measure these metrics.
* Data analysis: examination of data structures and contents,
* Documentation analysis,
* Analysis of technical environment (runtime and operations: hardware, operations environment, networks, operating systems involved and infrastructure software)
* Analysis of development processes (requirements engineering, design/implementation, test/QA and handover to operations)
* Analysis of operation processes
* Analysis of further processes and tasks that may influence development problems and system changes, e. g.,: management, budgeting, support, governance, outsourcing/offshoring, procurement.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
