// tag::DE[]
=== {learning-goals}

[[LZ-5-01]]
==== LZ 5-01: Entwickeln einer Verbesserungsstrategie

Softwarearchitekt:innen sollten:

* Geschäftsziele verstehen und Verbesserungen darauf ausrichten.
* Zukünftige Herausforderungen (Änderungen, Wachstum, Extremsituationen, Trends, Marktentwicklung, ...) im Blick haben und in der Verbesserungsstrategie berücksichtigen.
* Entscheidungsträger auf langfristige Verbesserungsprozesse vorbereiten, indem sie diese einbinden und über Ziele, Nutzen, Risiken, Hindernisse und Konsequenzen informieren und deren Zustimmung einholen.
* Durch Stakeholder-Management und mit kollaborativer Architekturarbeit Verständnis und ein Netz von Unterstützer:innen für Verbesserungen aufbauen.
* Methoden zur Entwicklung einer Verbesserungsstrategie angeben können, z. B.
** Architekturprinzipien (z. B. nach <<openGroup>>)
** Wardley Maps (siehe <<hiredThought>> und <<tune>>)
** Core Domain Charts (siehe <<dddCrew>> und <<tune>>)
** Nordstern (siehe <<geeks>> und <<tune>>)
* Aus den strategischen Überlegungen einen Plan entwickeln, der folgende Grundsätze befolgt (nach <<aim>>):
** Strebe nach schnellem und häufigem Feedback
** Führe Verbesserungen iterativ durch
** Teste Verbesserungen mit Prototypen
** Teste nach jeder Änderung
** Reduziere Komplexität
** Kommuniziere Annahmen explizit
** Gruppiere Verbesserungsmaßnahmen


[[LZ-5-02]]
==== LZ 5-02: Darstellen von bewerteten Problemen und Lösungsansätzen mit geeigneten Werkzeugen

Technische oder manuelle Ansätze zur expliziten Darstellung von bewerteten Problemen und Lösungsansätzen kennen und situationsangemessen auswählen – beispielsweise:

* Issue-Tracker
* Tabellen oder
* Datenbanken

[[LZ-5-03]]
==== LZ 5-03: Auswählen und kommunizieren methodischer Verbesserungsansätze

* Typische Ansätze für Verbesserung kennen, beispielsweise:

** Langfristige kontinuierliche Verbesserung
** Verbesserungs-Releases
** Application-Strangulation
** Kapselung (lokalisierbarer) Probleme oder Risiken in Blackboxes
** Extraktion fachlicher Teile, Abtrennung technischer Teile
** Schrittweise Ablösung problembehafteter Systemteile
** Rewrite
** Outsourcing
** Business Process Reengineering.

* Diese Ansätze für langfristige Verbesserung an unterschiedliche Stakeholder kommunizieren und argumentieren.

[[LZ-5-04]]
==== LZ 5-04: Abwägen der Effekte von „Rewrite" gegenüber „kontinuierlicher Verbesserung“

Softwarearchitekt:innen:
* Können die Effekte (Risiken, Vorteile) der Ansätze „komplette Neuentwicklung (Rewrite, _Big Bang_)“ gegenüber einer „kontinuierlichen Verbesserung“ einschätzen und argumentieren.
* Verstehen, dass mangelnde Kenntnis von Details (wie etwa Anforderungen, Details von Algorithmen und Prozessen, Qualitätsszenarien, Implementierungsdetails, technische Abhängigkeiten, betriebliche Prozesse) häufig die Option „Rewrite“ einfacher erscheinen lässt, als sie bei Berücksichtigung dieser Details wäre.
// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-5-01]]
==== LG 5-01: Develop an improvement strategy

Software architects should:

* Understand business objectives and align improvements with them.
* Watch for upcoming challenges (changes, growth, extreme situations, trends, market developments, etc.) and take them into account in the improvement strategy.
* Prepare decision-makers for long-term improvement processes by involving them, informing them about goals, benefits, risks, obstacles, and consequences, and obtaining their commitment.
* Build understanding and a network of supporters for improvements through stakeholder management and collaborative architecture work.
* State methods that can be used to develop an improvement strategy, such as the following:
** Architecture principles (e.g. according to <<openGroup>>)
** Wardley Maps (see <<hiredThought>> and <<tune>>)
** Core Domain Charts (see <<dddCrew>> and <<tune>>)
** North Star (see <<geeks>> and <<tune>>)
* Develop a plan based on strategic considerations that follows these principles (according to <<aim>>):
** Strive for rapid and frequent feedback
** Implement improvements iteratively
** Test improvements with prototype
** Test after every change
** Reduce complexity
** Communicate assumptions explicitly
** Group improvement.

[[LG-5-02]]
==== LG 5-02: Represent evaluated problems and solution approaches using appropriate tools

Know technical or manual approaches to explicitly represent evaluated problems and solution approaches and choose the appropriate for the given situation. Examples:

* Issue tracker
* Tables
* Databases.

[[LG-5-03]]
==== LG 5-03: Select and communicate methodical improvement approaches

* Know typical methods for improvement, e.g.,:

** Long-term continuous improvement,
** Improving releases,
** Application strangling,
** Encapsulation of (localized) problems or risks in black-boxes,
** Extraction of business aspects, separation of technical aspects,
** Incremental replacement of problematic parts of system,
** Rewrite,
** Outsourcing,
** Business process reengineering.

* Communicate and argue approaches to long-term improvement  to different stakeholders.

[[LG-5-04]]
==== LG 5-04: Weigh the effects of “rewrite” versus “continuous improvement”

Software architects:
* Can assess and argue the impact (risks, benefits) of a “complete rewrite” (_big bang_) approach in contrast to a “continuous improvement” approach in each situation.
* Understand that lack of details knowledge (e.g., requirements, details of algorithms and processes, quality scenarios, implementation details, technical dependencies, operational processes) often leads to the “rewrite” approach looking simpler as it would be when considering all the details.
// end::EN[]
