// tag::DE[]
=== {learning-goals}
[[LZ-5-01]]
==== LZ 5-01: Darstellen von bewerteten Problemen und Lösungsansätzen mit geeigneten Werkzeugen

Technische oder manuelle Ansätze zur expliziten Darstellung von bewerteten Problemen und Lösungsansätzen kennen und situationsangemessen auswählen – beispielsweise:

* Issue-Tracker
* Tabellen oder
* Datenbanken

[[LZ-5-02]]
==== LZ 5-02: Verbesserungspläne an Stakeholder kommunizieren und begründen

Softwarearchitekt:innen können diese Ansätze für langfristige Verbesserung an unterschiedliche Stakeholder kommunizieren und argumentieren.

// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-5-01]]
==== LG 5-01: Represent evaluated problems and solution approaches using appropriate tools

Know technical or manual approaches to explicitly represent evaluated problems and solution approaches and choose the appropriate for the given situation. Examples:

* Issue tracker
* Tables
* Databases.

[[LG-5-02]]
==== LG 5-02: Communicate and justify improvement plans to stakeholders

Software architects are able to communicate and justify these approaches to long-term improvement to different stakeholders.

// end::EN[]
