=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Bewertete Probleme und Lösungsansätze explizit darstellen

Technische oder manuelle Ansätze zur expliziten Darstellung von bewerteten Problemen und Lösungsansätzen kennen
und situationsangemessen auswählen – beispielsweise:

* Issue-Tracker
* Tabellen oder
* Datenbanken

[[LZ-4-2]]
==== LZ 4-2: Typische methodische Ansätze für Verbesserung

* Typische Ansätze für Verbesserung kennen, beispielsweise:
** Langfristige kontinuierliche Verbesserung
** Verbesserungs-Releases
** Application-Strangulation
** Kapselung (lokalisierbarer) Probleme oder Risiken in Blackboxes
** Extraktion fachlicher Teile, Abtrennung technischer Teile
** Schrittweise Ablösung problembehafteter Systemteile
** Rewrite
** Outsourcing
** Business Process Reengineering.

* Diese Ansätze für langfristige Verbesserung an unterschiedliche Stakeholder kommunizieren und argumentieren.

[[LZ-4-3]]
==== LZ 4-3: Effekte von „Rewrite“ versus „kontinuierliche Verbesserung“

* In einer gegebenen Situation die Effekte (Risiken, Vorteile) der Ansätze „komplette Neuentwicklung (Rewrite)“ gegenüber einer „kontinuierlichen Verbesserung“ einschätzen und argumentieren können.
* Verstehen, dass mangelnde Kenntnis von Details (wie etwa Anforderungen, Details von Algorithmen und Prozessen, Qualitätsszenarien, Implementierungsdetails, technische Abhängigkeiten, betriebliche Prozesse) häufig die Option „Rewrite“ einfacher erscheinen lässt, als sie bei Berücksichtigung dieser Details wäre.

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Explicitly represent evaluated problems and solution approaches

Understand and utilize technical or manual methods to clearly document and represent evaluated problems and solution approaches, selecting the most suitable option for the given situation and stakeholders.

* Example tools: Issue trackers, spreadsheets, presentations, diagrams, reports, dashboards
* Example methodologies:
** Causal chains (problem and causes in relationship to each other)
** Quality views / risk storming (diagram-based visualizations of problems and improvement activities)
** Gap analysis (current state, future state, gaps, and remedies)
** Architecture decision records (problem context and selected solution approaches)
** Technology radar / roadmaps (tracking and planning technology and improvement adoption)

[[LG-4-2]]
==== LG 4-2: Typical methodical approaches for improvement

* Understand and utilize typical methods for improvement, including:
** Business process reengineering
** Incremental replacement of problematic system components
** Application strangulation
** Long-term continuous improvement
** Extraction and separation of business and technical aspects
** Outsourcing non-differantiating development acticitiys and duties

* Effectively communicate and motivate these long-term improvements to various stakeholders.


[[LG-4-3]]
==== LG 4-3: Impact of “rewrite” versus “continuous improvement”

* Being able to assess and argue the impact (risks, benefits) of a “complete rewrite” approach in contrast to a “continuous improvement” approach in each situation.
* Understand that lack of details knowledge (e.g., requirements, details of algorithms and processes, quality scenarios, implementation details, technical dependencies, operational processes) often leads to the “rewrite” approach looking simpler as it would be when considering all the details.

// end::EN[]


