// tag::DE[]
=== {learning-goals}
[[LZ-4-01]]
==== LZ 4-01: Bewertete Probleme und Lösungsansätze explizit darstellen

Technische oder manuelle Ansätze zur expliziten Darstellung von bewerteten Problemen und Lösungsansätzen kennen und situationsangemessen auswählen – beispielsweise:

* Issue-Tracker
* Tabellen oder
* Datenbanken

[[LZ-4-02]]
==== LZ 4-02: Typische methodische Ansätze für Verbesserung

* Typische Ansätze für Verbesserung kennen, beispielsweise:

** Langfristige kontinuierliche Verbesserung
** Verbesserungs-Releases
** Application-Strangulation
** Kapselung (lokalisierbarer) Probleme oder Risiken in Blackboxes
** Extraktion fachlicher Teile, Abtrennung technischer Teile
** Schrittweise Ablösung problembehafteter Systemteile
** Rewrite
** Outsourcing
** Business Process Reengineering.

* Diese Ansätze für langfristige Verbesserung an unterschiedliche Stakeholder kommunizieren und argumentieren.

[[LZ-4-03]]
==== LZ 4-03: Effekte von „Rewrite“ versus „kontinuierliche Verbesserung“

* In einer gegebenen Situation die Effekte (Risiken, Vorteile) der Ansätze „komplette Neuentwicklung (Rewrite)“ gegenüber einer „kontinuierlichen Verbesserung“ einschätzen und argumentieren können.
* Verstehen, dass mangelnde Kenntnis von Details (wie etwa Anforderungen, Details von Algorithmen und Prozessen, Qualitätsszenarien, Implementierungsdetails, technische Abhängigkeiten, betriebliche Prozesse) häufig die Option „Rewrite“ einfacher erscheinen lässt, als sie bei Berücksichtigung dieser Details wäre.
// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-4-01]]
==== LG 4-01: Explicitly represent evaluated problems and solution approaches

Know technical or manual approaches to explicitly represent evaluated problems and solution approaches and choose the appropriate for the given situation. Examples:

* Issue tracker
* Tables
* Databases.

[[LG-4-02]]
==== LG 4-02: Typical methodical approaches for improvement

* Know typical methods for improvement, e.g.,:

** Long-term continuous improvement,
** Improving releases,
** Application strangling,
** Encapsulation of (localized) problems or risks in black-boxes,
** Extraction of business aspects, separation of technical aspects,
** Incremental replacement of problematic parts of system,
** Rewrite,
** Outsourcing,
** Business process reengineering.

* Communicate and argue approaches to long-term improvement  to different stakeholders.

[[LG-4-03]]
==== LG 4-03: Impact of “rewrite” versus “continuous improvement”

* Being able to assess and argue the impact (risks, benefits) of a “complete rewrite” approach in contrast to a “continuous improvement” approach in each situation.
* Understand that lack of details knowledge (e.g., requirements, details of algorithms and processes, quality scenarios, implementation details, technical dependencies, operational processes) often leads to the “rewrite” approach looking simpler as it would be when considering all the details.
// end::EN[]


