
// tag::DE[]
[[LZ-4-3]]
==== LZ 4-3: Effekte von „Rewrite“ versus „kontinuierliche Verbesserung“

* In einer gegebenen Situation die Effekte (Risiken, Vorteile) der Ansätze „komplette Neuentwicklung (Rewrite) gegenüber einer „kontinuierlichen Verbesserung“ einschätzen und argumentieren können.
* Verstehen, dass mangelnde Kenntnis von Details (wie etwa Anforderungen, Details von Algorithmen und Prozessen, Qualitätsszenarien, Implementierungsdetails, technische Abhängigkeiten, betriebliche Prozesse) häufig die Option „Rewrite“ einfacher erscheinen lässt, als sie bei Berücksichtigung dieser Details wäre.

// end::DE[]

// tag::EN[]
[[LG-4-3]]
==== LG 4-3: Assess the impact of “rewrite“ versus “continuous improvement"

* Being able to assess and argue the impact (risks, benefits) of a “complete rewrite” approach in contrast to a “continuous improvement“ approach in each situation.

* Understand that lack of details knowledge (e. g., requirements, details of algorithms and processes, quality scenarios, implementation details, technical dependencies, operational processes) often leads to the “rewrite” approach looking simpler as it would be when considering all the details.

// end::EN[]

