=== {learning-goals}

// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Möglichkeiten zur Optimierung von Entwicklungsprozessen

* Dezentralisierung bzw. Zentralisierung von Entwicklungsprozessen.
* Einsatz iterativer Prozesse zur Reduktion von Risiken.
* Verringerung von Wartezeiten und Puffern zur Beschleunigung von Entwicklungsprozessen.
* Identifikation kritischer Bestandteile (Personen, Organisationseinheiten) in Entwicklungsprozessen und deren Entlastung.

[[LZ-5-2]]
==== LZ 5-2: Verbesserungsmaßnahmen im Quellcode

* Für Technologien/Programmiersprachen typische Refactorings (bedeutungserhaltende Vereinfachungsmassnahmen im Quellcode) kennen und anwenden können. In Schulungen sollten bei Bedarf entsprechende Übungen durchgeführt werden.
* Technologien besser nutzen und bessere Technologie einführen (Technologiewechsel).
* Zusammenhang zwischen technischen Schulden und Refactoring erklären können.
* Maßnahmen und Muster zur Reduktion von Kopplung in Quellcode kennen und anwenden können.
* Maßnahmen und Muster zur Verbesserung der Verständlichkeit von Quellcode kennen und anwenden können, beispielsweise Clean-Code-Prinzipien.

[[LZ-5-3]]
==== LZ 5-3: Möglichkeiten des automatisierten Tests zur Reduktion von Änderungsrisiken

* Automatisierte Tests (Unit-, Integrations-, Akzeptanz-, Regressionstests) als Mittel zur Früherkennung von Fehlern in Änderungs- oder Verbesserungsprojekten kennen und selbständig anwenden können (In Schulungen sollten bei Bedarf entsprechende Übungen durchgeführt werden).
* Selbständig identifizieren können, an welchen Stellen/Schnittstellen/Komponenten die Einführung automatisierter Tests für bestimmte Änderungsszenarien angemessen ist.

[[LZ-5-4]]
==== LZ 5-4: Automatisierung als Mittel zur Reduktion von Änderungsrisiken

Weitere methodische und technische Mittel zur Automatisierung kennen, mit deren Hilfe systematisch Änderungsrisiken und -aufwände gesenkt werden können, beispielsweise:

* Continuous Integration
* Continuous Delivery
* Model-driven Development/Generative Development

[[LZ-5-5]]
==== LZ 5-5: Relevante Architektur-/Entwurfs- oder Implementierungsmuster zur Reduktion von Kopplung innerhalb von Systemen

* Typische Muster zur Reduktion von Kopplung kennen und anwenden können (beispielsweise Modularisierung/Komponentenbildung, Entkopplung über Interfaces, Dependency-Injection, Kapselung, Adapter, Wrapper, Gateway), zeitliche Entkopplung über Asynchronität).
* Effekte typischer Muster (ggfs. unter Zuhilfenahme entsprechender Werkzeuge) nachvollziehen können.

[[LZ-5-6]]
==== LZ 5-6: Technologiespezifische Möglichkeiten zur Verbesserung des Laufzeitverhaltens von Systemen

Technologiespezifische Muster und Praktiken zur Verbesserung von Laufzeiteigenschaften kennen und anwenden können (die detaillierte Auswahl obliegt dem Schulungs-/Trainingsanbieter).

[[LZ-5-7]]
==== LZ 5-7: Möglichkeiten zur Verbesserung betrieblicher Prozesse

(Unter Umständen technologiespezifische) Muster und Praktiken zur Verbesserung der Betreibbarkeit kennen (die detaillierte Auswahl obliegt dem Schulungs-/Trainingsanbieter).

[[LZ-5-8]]
==== LZ 5-8: Möglichkeiten zur Verbesserung der Dokumentation oder Dokumentationsprozesse

Grundlegende Möglichkeiten zur systematischen Verbesserung von technischer Dokumentation kennen und anwenden können, beispielsweise:

* Einhaltung etablierter Dokumentationsstrukturen (z. B. Templates)
* Gezielte Reduktion von Dokumentationsumfang durch Abstraktion oder inhaltliche Fokussierung
* Top-Down-Kommunikation
* Trennung struktureller (spezifischer) und konzeptioneller (übergreifender) Inhalte
* Modularisierung von Dokumentation

// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Potential approaches to optimize development processes

* Decentralization vs. centralization of development processes.
* Employment of iterative processes to reduce risks.
* Reduce idle times and buffers to accelerate development processes.
* Identify critical parts (people, organizational units) in development processes and possible ways to relieve them.

[[LG-5-2]]
==== LG 5-2: Improvement measures for source code

* Know and being able to apply typical technology/programming language-specific refactorings (semantics preserving simplification measures in source code). Training should conduct exercises if required.
* Better use of technology or use better technology (change of technology).
* Explain the connection between technical debts and refactoring.
* Know and be able to apply measures and patterns to reduce coupling at source code level.
* Know and be able to apply measures and patterns to make source code more comprehensible, e. g., Clean Code principles.

[[LG-5-3]]
==== LG 5-3: Possible approaches for automated testing to reduce risks of change

* Know and being able to autonomously apply automated tests (unit-, integration-, acceptance-, regression-tests) as a means of early detection of defects in change or improvement projects. (Training should provide exercises if required.)
* Being able to autonomously identify adequate locations/interfaces/components where the introduction of automated tests will be suitable for specific change scenarios.

[[LG-5-4]]
==== LG 5-4: Automation as a means of reducing risks of changes

Know further methodical and technical means of automation that may help to reduce risk and required efforts of changes, such as:

* Continuous integration
* Continuous delivery
* Model-driven development/generative development

[[LG-5-5]]
==== LG 5-5: Relevant architectural-/design- or implementation patterns to reduce system-internal coupling

* Know and be able to apply typical patterns to reduce coupling (e. g., modularization/component building, decoupling via interfaces, dependency injection, encapsulation, adapter, wrapper, gateway, decoupling of control flow with asynchronous invocation).
* Understand the impact of typical patterns (possibly by using appropriate tools).

[[LG-5-6]]
==== LG 5-6: Technology-specific options to improve the runtime behavior of systems

Know and be able to apply technology-specific patterns and practices to improve runtime properties (specific choices are at the training provider’s discretion).

[[LG-5-7]]
==== LG 5-7: Options to improve operation processes

(Possibly technology specific) patterns and practices to improve system operations (specific choices are at the training provider’s discretion).

[[LG-5-8]]
==== LG 5-8: Options to improve the documentation or the documentation processes

Know and be able to apply basic options for systematic improvement of technical documentation, such as:

* Compliance with established document structures (e. g., templates)
* Targeted reduction of documentation volume through abstraction or focussing on essential topics
* Top-down communication,
* Separation of structural (specific) and conceptual (overarching) contents.
* Modularization of documentation

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
