=== {learning-goals}

// tag::DE[]
[[LZ-5-01]]
==== LZ 5-01: Möglichkeiten zur Optimierung von Entwicklungsprozessen

* Dezentralisierung bzw. Zentralisierung von Entwicklungsprozessen.
* Einsatz iterativer Prozesse zur Reduktion von Risiken.
* Verringerung von Wartezeiten und Puffern zur Beschleunigung von Entwicklungsprozessen.
* Identifikation kritischer Bestandteile (Personen, Organisationseinheiten) in Entwicklungsprozessen und deren Entlastung.

[[LZ-5-02]]
==== LZ 5-02: Verbesserungsmaßnahmen im Quellcode

* Für Technologien/Programmiersprachen typische Refactorings (verhaltenserhaltende Vereinfachungsmaßnahmen im Quellcode) kennen.
* Technologien besser nutzen und bessere Technologie einführen (Technologiewechsel).
* Zusammenhang zwischen technischen Schulden und Refactoring erklären können.
* Maßnahmen und Muster zur Reduktion von Kopplung in Quellcode kennen und beurteilen können.
* Maßnahmen und Muster zur Verbesserung der Verständlichkeit von Quellcode kennen, beispielsweise Clean-Code-Prinzipien.

[[LZ-5-03]]
==== LZ 5-03: Möglichkeiten der Automatisierung zur Reduktion von Änderungsrisiken identifizieren, auswählen und anwenden

Softwarearchitekt:innen sollten beispielsweise:

* automatisierte Tests (Unit-, Integrations-, Akzeptanz-, Regressionstests) als Mittel zur Früherkennung von Fehlern nach Änderungen konzipieren und umsetzen können,
* erkennen können, an welchen Stellen (etwa: Schnittstellen oder Komponenten) automatisierte Tests angemessen oder notwendig sind,
* weitere Methoden der Automatisierung kennen, die systematisch Änderungsrisiken und -aufwände reduzieren können, beispielsweise: 
** Continuous Integration
** Continuous Delivery
** Model-driven Development/Generative Development
** Infrastructure-As-Code
** Docs-As-Code
** Diagrams-As-Code


[[LZ-5-05]]
==== LZ 5-05: Muster oder Lösungsansätze zur Reduktion von Kopplung innerhalb von Systemen auswählen und anwenden

Softwarearchitekt:innen:

* kennen typische Muster oder Lösungsansätze zur Reduktion von Kopplung und können diese anwenden (beispielsweise Modularisierung/Komponentenbildung, Entkopplung über Interfaces, Dependency-Injection, Kapselung, Adapter, Wrapper, Gateway), zeitliche Entkopplung über Asynchronität)
* können deren Effekte (Wirkungen und Nebenwirkungen), ggfs. unter Zuhilfenahme entsprechender Werkzeuge, nachvollziehen.

[[LZ-5-06]]
==== LZ 5-06: Identifizieren, auswählen und anwenden von Ansätzen zur Lösung von Problemen mit Anwendungsdaten und Datenbanken.

Siehe <<LZ-2-09>>.

Beispiele für solche Ansätze sind:

* _Deprecation Period_ für Datenbank-Refactoring (siehe <<amblersadalage>>).
* Aufteilen oder Zusammenführen von Datenbanken zur Verbesserung der erforderlichen Eigenschaften.
* Anpassen von Datenstrukturen/-typen an aktuelle Anforderungen, einschließlich Entwerfen und Implementieren von Datenmigrationen.
* Technische Optionen wie Indizierung, Caching, Abfrageoptimierung, Partitionierung, Sharding
* Techniken zur Erreichung oder Aufrechterhaltung der Konsistenz über replizierte oder verteilte Daten hinweg.

Softwarearchitekt:innen kennen die Herausforderungen von:

* gemeinsam genutzten, verteilten oder replizierten Daten, wie Schreibkonflikte, Integritätsverletzungen, Inkonsistenzen.
* Versionierung von Datenstrukturen und Daten.


[[LZ-5-07]]
==== LZ 5-07: Technologiespezifische Möglichkeiten zur Verbesserung des Laufzeitverhaltens von Systemen

Technologiespezifische Muster und Praktiken zur Verbesserung von Laufzeiteigenschaften kennen und anwenden können (die detaillierte Auswahl obliegt dem Schulungs-/Trainingsanbieter).

[[LZ-5-08]]
==== LZ 5-08: Möglichkeiten zur Verbesserung betrieblicher Prozesse

(Unter Umständen technologiespezifische) Muster und Praktiken zur Verbesserung der Betreibbarkeit kennen (die detaillierte Auswahl obliegt dem Schulungs-/Trainingsanbieter).

[[LZ-5-09]]
==== LZ 5-09: Möglichkeiten zur Verbesserung der Dokumentation oder Dokumentationsprozesse

Grundlegende Möglichkeiten zur systematischen Verbesserung von technischer Dokumentation kennen und anwenden können, beispielsweise:

* Einhaltung etablierter Dokumentationsstrukturen (z. B. Templates)
* Gezielte Reduktion von Dokumentationsumfang durch Abstraktion oder inhaltliche Fokussierung
* Top-Down-Kommunikation
* Trennung struktureller (spezifischer) und konzeptioneller (übergreifender) Inhalte
* Modularisierung von Dokumentation

// end::DE[]

// tag::EN[]
[[LG-5-01]]
==== LG 5-01: Identify, select and apply approaches to improve development processes

* Decentralization vs. centralization of development processes.
* Employment of iterative processes to reduce risks.
* Reduce idle times and buffers to accelerate development processes.
* Identify critical parts (people, organizational units) in development processes and possible ways to relieve them.

[[LG-5-02]]
==== LG 5-02: Identify, select and apply approaches to improve source code

* Know and assess typical technology/programming language-specific refactorings (semantics preserving simplification measures in source code).
* Better use of technology or use better technology (change of technology).
* Explain the connection between technical debts and refactoring.
* Know and be able to assess measures and patterns to reduce coupling at source code level.
* Know measures and patterns to make source code more comprehensible, e.g., Clean Code principles.


[[LG-5-03]]
==== LG 5-03: Identify, select, and apply automation options to reduce change risks

Software architects should, for example:

* be able to design and implement automated tests (unit, integration, acceptance, regression tests) as a means of early detection of errors after changes,
* be able to recognize where (e.g., interfaces or components) automated tests are appropriate or necessary,
* be familiar with other automation methods that can systematically reduce change risks and effort, for example: 
** Continuous integration
** Continuous delivery
** Model-driven development/generative development
** Infrastructure-as-code
** Docs-as-code
** Diagrams-as-code


[[LG-5-05]]
==== LG 5-05: Identify, select and apply patterns or approaches to improve issues related to coupling

Software architects:
* know typical patterns or approaches to reduce internal coupling and can apply these (e.g., modularization/component building, decoupling via interfaces, dependency injection, encapsulation, adapter, wrapper, gateway, decoupling of control flow with asynchronous invocation).
* understand their impact (effects and side-effects), possibly by using appropriate tools.


[[LG-5-06]]
==== LG 5-06: Identify, select and apply approaches to address issues with application data and databases

See <<LG-2-09>>.

Examples of such approaches include:

* _Deprecation period_ pattern for database refactoring (see <<amblersadalage>>).
* Splitting or merging databases to improve required qualities.
* Adjusting data structures/types to current requirements, including designing and implementing data migrations.
* Technical options like indexing, caching, query optimization, partitioning, sharding 
* Techniques to achieve or maintain consistency across replicated or distributed data.

Software architects know the challenges of:

* shared, distributed or replicated data, like write conflicts, integrity violations, inconsistencies.
* versioning of data structures and data.


[[LG-5-07]]
==== LG 5-07: Identify, select and apply technology-specific approaches to improve issues related to runtime behavior 

Know and be able to apply technology-specific patterns and practices to improve runtime properties (specific choices are at the training provider’s discretion).

[[LG-5-08]]
==== LG 5-08: Identify, select and apply approaches to improve issues related to operation processes

(Possibly technology specific) patterns and practices to improve system operations (specific choices are at the training provider’s discretion).

[[LG-5-09]]
==== LG 5-09: Identify, select and apply approaches to improve issues related to documentation or documentation processes

Know and be able to apply basic options for systematic improvement of technical documentation, such as:

* Compliance with established document structures (e.g., templates)
* Targeted reduction of documentation volume through abstraction or focussing on essential topics
* Top-down communication,
* Separation of structural (specific) and conceptual (overarching) contents.
* Modularization of documentation

// end::EN[]


