// tag::DE[]
[[LZ-5-8]]
==== LZ 5-8: Möglichkeiten zur Verbesserung der Dokumentation oder Dokumentationsprozesse kennen

Grundlegende Möglichkeiten zur systematischen Verbesserung von technischer Dokumentation kennen und anwenden können, beispielsweise:
* Einhaltung etablierter Dokumentationsstrukturen (z. B. Templates)
* Gezielte Reduktion von Dokumentationsumfang durch Abstraktion oder inhaltliche Fokussierung
* Top-Down-Kommunikation
* Trennung struktureller (spezifischer) und konzeptioneller (übergreifender) Inhalte
* Modularisierung von Dokumentation

// end::DE[]

// tag::EN[]
[[LG-5-8]]
==== LG 5-8: Know options to improve the documentation or the documentation processes

Know and be able to apply basic options for systematic improvement of technical documentation, such as:

* Compliance with established document structures (e. g., templates)
* Targeted reduction of documentation volume through abstraction or focussing on essential topics
* Top-down communication,
* Separation of structural (specific) and conceptual (overarching)
contents.
* Modularisation of documentation

// end::EN[]
