// tag::DE[]
[[LZ-5-2]]
==== LZ 5-2: Verbesserungsmaßnahmen im Quellcode kennen und anwenden können

* Für Technologien/Programmiersprachen typische Refactorings (bedeutungserhaltende Vereinfachungsmassnahmen im Quellcode) kennen und anwenden können. In Schulungen sollten bei Bedarf entsprechende Übungen durchgeführt werden. 
* Technologien besser nutzen und bessere Technologie einführen (Technologiewechsel).
* Zusammenhang zwischen technischen Schulden und Refactoring erklären können. 
* Maßnahmen und Muster zur Reduktion von Kopplung in Quellcode kennen und anwenden können.
* Maßnahmen und Muster zur Verbesserung der Verständlichkeit von Quellcode kennen und anwenden können, beispielsweise Clean-Code-Prinzipien.

// end::DE[]

// tag::EN[]
[[LG-5-2]]
==== LG 5-2: Know and being able to apply improvement measures for source code

* Know and being able to apply typical technology/programming language
specific refactorings (semantics preserving simplification measures in source code). Trainings should conduct exercises if required.
* Better use of technology or use better technology (change of technology).
* Explain the connection between technical debts and refactoring.
* Know and be able to apply measures and patterns to reduce coupling at source code level.
* Know and be able to apply measures and patterns to make source code more comprehensible, e. g., Clean Code principles.

// end::EN[]
