// tag::DE[]
[[LZ-5-5]]
==== LZ 5-5: Relevante Architektur-/Entwurfs- oder Implementierungsmuster zur Reduktion von Kopplung innerhalb von Systemen kennen

* Typische Muster zur Reduktion von Kopplung kennen und anwenden können (beispielsweise Modularisierung/Komponentenbildung, Entkopplung über Interfaces, Dependency-Injection, Kapselung, Adapter, Wrapper, Gateway), zeitliche Entkopplung über Asynchronität). 
* Effekte typischer Muster (ggfs. unter Zuhilfenahme entsprechender Werkzeuge) nachvollziehen können.  

// end::DE[]

// tag::EN[]
[[LG-5-5]]
==== LG 5-5: Know relevant architectural-/design- or implementation patterns to reduce system-internal coupling

* Know and be able to apply typical patterns to reduce coupling (e. g., modularisation/component building, decoupling via interfaces, dependency injection, encapsulation, adapter, wrapper, gateway, decoupling of control flow with asynchronous invocation).
* Understand the impact of typical patterns (possibly by using appropriate tools).

// end::EN[]
