// tag::DE[]
== Allgemeines zum iSAQB Advanced Level

=== iSAQB und CPSA-A
Der _International Software Architecture Qualification Board_ (iSAQB(R)) bringt Expert*innen für Softwarearchitektur
aus Industrie, Beratung, Ausbildung, Wissenschaft und anderen Organisationen zusammen.

Sein Programm _Certified Professional for Software Architecture_ (CPSA(R) ) bietet Softwarearchitekt*innen
standardisierte Schemata für die Ausbildung, die weltweit anerkannt sind. Mehr dazu unter https://isaqb.org.

// end::DE[]

// tag::EN[]
== General information about the iSAQB Advanced Level

=== On iSAQB and CPSA-A

The _International Software Architecture Qualification Board_ (iSAQB(R)) brings together professional software architecture experts from industry, consulting, training, academia and other organisations.

Its _Certified Professional for Software Architecture_ programme (CPSA(R) ) provides software architects with standardised schemes for training that is globally recognised. More on https://isaqb.org.

// end::EN[]

include::01-what-to-expect-of-an-advanced-level-module.adoc[{include_configuration}]

include::02-advanced-level-knowledge.adoc[{include_configuration}]

include::03-prerequisites.adoc[{include_configuration}]
