// tag::DE[]
=== {learning-goals}
[[LZ-3-01]]
==== LZ 3-01: Argumentieren mittels betriebswirtschaftlicher Größen 

* Architekt:innen wissen, welche Verbindungen zwischen _Kosten_ und _Wert_ existieren (andere Begriffe hierfür sind _Aufwand_ und _Nutzen_).
* Sie können verschiedene betriebswirtschaftlicher Größen nutzen, um mögliche Verbesserungen gegenüber anderen Stakeholdern zu motivieren und zu argumentieren.
    Dabei können sie:
** Zwischen direkten (z.B. für Entwicklung oder Betrieb) und indirekten Kosten (z.B. für Kontextwechsel oder Verzögerungen) von Investitionen für realistischere Schätzungen unterscheiden.
** Langfristige Investitionen in Vermögenswerte (CAPEX) von laufenden Betriebsausgaben für den täglichen Betrieb (OPEX) unterscheiden, um einen passenden Grad an Flexibilität zu erreichen  (siehe <<capexopex>>).
** Bereits genehmigte strategische Initiativen nutzen, um Verbesserungsmaßnahmen an diesen Prioritäten auszurichten und zu verknüpfen.
** Vorgegebene IT-Budgetstrukturen wie 'Plan – Build – Run' für Verbesserungen ausnutzen.
** Grundlegende Argumentationslinien unter Anwendung wirtschaftlicher Konzepte wie ROI, Break-Even-Analyse, Abschreibungen und Amortisation verstehen.
** Geeignete Wege zur Zuordnung von Problem- und Verbesserungskosten auf der Basis von Kostentreibern (intern und extern) finden.
** Potenzielle Kosten im Zusammenhang mit Risiken und technische Schulden identifizieren, einschließlich Auswirkungen auf Projektlaufzeiten und möglicher Schäden am Unternehmensruf.

[[LZ-3-02]]
==== LZ 3-02: Unterscheiden zwischen Schätzung, Beobachtung und Messung

* Begriffe „Schätzung“, „Beobachtung“ und „Messung“ erklären und in der Evaluierung von Problemen und Lösungsansätzen anwenden
* Schätzungen in Intervallen angeben können. Sie kennen verschiedene Ansätze für Intervallschätzungen:
** Konfidenzintervall
** Minimum-Maximum-Intervall
** Worst-/Average-/Best-Case-Schätzung
* Wahrscheinlichkeit der Korrektheit von Schätzungen beurteilen und angeben können (etwa durch Größe von Intervallschätzungen)
* Schätzgegenstände identifizieren und benennen, beispielsweise Arbeitsstunden
* Schätzparameter und Einflussfaktoren auf Schätzungen identifizieren
* Explizite Annahmen treffen, um Schätzparameter in Wertebereichen festlegen zu können.

[[LZ-3-03]]
==== LZ 3-03: Schätzen von Problemen und Lösungsansätzen

Softwarearchitekt:innen können Schätzverfahren auf Probleme und Lösungsansätze anwenden.

Insbesondere können sie die durch Probleme oder Risiken verursachten (potentiellen) Schäden (_Schmerzen_) quantitativ einschätzen.
// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-3-01]]
==== LG 3-01: Argue contextually using business metrics


* Architects understand the connections between _costs_ and _value_ (other terms are _effort_ and _benefit_).
* They know and utilize various business metrics to find the ideal approach for motivating improvements. In doing so, they can:
** Differentiate between direct costs (e.g., for development or operations) and indirect costs (e.g., for context switching or delays) of investments for more realistic estimates.
** Distinguish between long-term investments in assets (CAPEX) and ongoing operating expenses for daily operations (OPEX) to achieve an appropriate level of flexibility (see <<capexopex>>).
** Leverage already approved strategic initiatives to align and connect improvement efforts with these priorities.
** Utilize predefined IT budget structures such as 'Plan – Build – Run' to drive improvements.
** Understand basic lines of argument using economic concepts like ROI, break-even analysis, depreciation, and amortization.
** Find appropriate ways to allocate problem and improvement costs based on cost drivers (internal and external).
** Identify potential costs associated with risks and technical debt, including impacts on project timelines and possible damage to the company's reputation.

[[LG-3-02]]
==== LG 3-02: Differentiate between estimation, observation, and measurement

* Explain the terms “estimation”, “observation”, and “measurement” and apply them to the evaluation of problems and solution approaches.
* Be able to estimate efforts in intervals. Know different approaches for interval estimates:
** Confidence interval,
** Minimum/maximum interval,
** Worst-/Average-/Best-Case estimation.
* Be able to assess and communicate the probability of the correctness of the estimation.
* Identify and name items to be estimated, e.g., hours of work.
* Identify parameters and influencing factors of estimations
* explicit assumption to be able to define estimation parameters in value ranges.

[[LG-3-03]]
==== LG 3-03: Estimate for problems and solution approaches

Software architects can apply estimation techniques to problems and solution approaches.

In particular, they can quantitatively assess the (potential) damage (_pain_) caused by problems or risks.

// end::EN[]
