// tag::DE[]
=== {learning-goals}
[[LZ-3-01]]
==== LZ 3-01: Argumentieren mittels betriebswirtschaftlicher Größen

* Architekt:innen wissen, welche Verbindungen zwischen _Kosten_ und _Wert_ existieren (andere Begriffe hierfür sind _Aufwand_ und _Nutzen_).
* Sie können verschiedene betriebswirtschaftliche Größen nutzen, um mögliche Verbesserungen gegenüber anderen Stakeholdern zu motivieren und zu argumentieren.
    Dabei können sie:
** Zwischen direkten (z.B. für Entwicklung oder Betrieb) und indirekten Kosten (z.B. für Kontextwechsel oder Verzögerungen) von Investitionen für realistischere Schätzungen unterscheiden.
** Langfristige Investitionen in Vermögenswerte (CAPEX) von laufenden Betriebsausgaben für den täglichen Betrieb (OPEX) unterscheiden, um einen passenden Grad an Flexibilität zu erreichen (siehe <<capexopex>>).
** Bereits genehmigte strategische Initiativen nutzen, um Verbesserungsmaßnahmen an diesen Prioritäten auszurichten und zu verknüpfen.
** Vorgegebene IT-Budgetstrukturen wie 'Plan – Build – Run' für Verbesserungen ausnutzen.
** Grundlegende Argumentationslinien unter Anwendung wirtschaftlicher Konzepte wie ROI, Break-Even-Analyse, Abschreibungen und Amortisation verstehen.
** Potenzielle Kosten im Zusammenhang mit Risiken und technischen Schulden identifizieren, einschließlich Auswirkungen auf Projektlaufzeiten und möglicher Schäden am Unternehmensruf.

[[LZ-3-02]]
==== LZ 3-02: Schätzen von Problemen und Lösungsansätzen

* Schätzungen in Intervallen angeben können
* Wahrscheinlichkeit der Korrektheit von Schätzungen beurteilen und angeben können
* Schätzparameter und Einflussfaktoren auf Schätzungen identifizieren
* Annahmen und Einflussfaktoren offenlegen, um die Schätzungen transparent und reproduzierbar zu halten


[[LZ-3-03]]
==== LZ 3-03: Ganzheitliche Bewertung von Modernisierungsstrategien

Als eine zentrale Anwendung von Schätz- und Bewertungsverfahren können Softwarearchitekt:innen die Auswirkungen vielfältiger Modernisierungsstrategien abwägen.

Insbesondere können sie:

* Ein breites Spektrum an Lösungsansätzen bewerten, Effekte (Risiken, Vorteile, Aufwände) kontextbezogen einschätzen und argumentieren.
* Die trügerische Einfachheit von Rewrites erkennen: Verstehen, dass mangelnde Kenntnis von existierenden Details (wie etwa Anforderungen, Algorithmen und Prozesse, Qualitätsszenarien, Implementierungsdetails, technische Abhängigkeiten und betriebliche Prozesse) radikale Optionen wie den "Rewrite" häufig wesentlich einfacher erscheinen lässt, als sie bei Berücksichtigung dieser Details tatsächlich wären.
* Wissen sichern und Risiken minimieren: Erkennen, dass vor drastischen Architekturentscheidungen oft vorgeschaltete Strategien (wie *Extract* zur Wissenssicherung oder *Trim it down* zur Reduktion von Ballast) notwendig sind, um fundierte Entscheidungen treffen zu können.
// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-3-01]]
==== LG 3-01: Argue contextually using business metrics

* Architects understand the connections between _costs_ and _value_ (other terms are _effort_ and _benefit_).
* They know and utilize various business metrics to motivate and argue for improvements. In doing so, they can:
** Differentiate between direct costs (e.g., for development or operations) and indirect costs (e.g., for context switching or delays) of investments for more realistic estimates.
** Distinguish between long-term investments in assets (CAPEX) and ongoing operating expenses for daily operations (OPEX) to achieve an appropriate level of flexibility (see <<capexopex>>).
** Leverage already approved strategic initiatives to align and connect improvement efforts with these priorities.
** Utilize predefined IT budget structures such as 'Plan – Build – Run' to drive improvements.
** Understand basic lines of argument using economic concepts like ROI, break-even analysis, depreciation, and amortization.
** Find appropriate ways to allocate problem and improvement costs based on cost drivers (internal and external).
** Identify potential costs associated with risks and technical debt, including impacts on project timelines and possible damage to the company's reputation.

[[LG-3-02]]
==== LG 3-02: Differentiate between estimation, observation, and measurement

* Explain the terms "estimation", "observation", and "measurement" and apply them to the evaluation of problems and solution approaches.
* Be able to state estimates in intervals. Know different approaches for interval estimates:
** Confidence interval
** Minimum/maximum interval
** Worst-/Average-/Best-Case estimation
* Be able to assess and communicate the probability of the correctness of estimations.
* Identify and name items to be estimated, e.g., hours of work.
* Identify parameters and influencing factors of estimations.
* Make assumptions explicit to be able to define estimation parameters in value ranges.

[[LG-3-03]]
==== LG 3-03: Estimate problems and solution approaches

Software architects can apply estimation techniques to problems and solution approaches.

In particular, they can:

* quantitatively assess the (potential) damage (_pain_) caused by problems or risks,
* state assumptions and influencing factors when estimating, and record plausible ranges for these factors to keep estimates transparent and reproducible.


[[LG-3-04]]
==== LG 3-04: Evaluate macro-strategies: Rewrite vs. incremental improvement

As a key application of estimation and assessment, software architects can weigh the effects of major, opposing improvement strategies (which are detailed in <<LG-4-01>>).

They can, in particular:
* Assess and argue the impact (risks, benefits) of a "complete rewrite" (_big bang_) approach in contrast to a "continuous improvement" approach.
* Understand that a lack of detailed knowledge (e.g., of requirements, details of algorithms and processes, quality scenarios, implementation details, technical dependencies, or operational processes) often makes the "rewrite" option appear simpler than it actually is.
// end::EN[]