=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Mittels betriebswirtschaftlicher Größen situativ argumentieren

* Architekt:innen wissen, welche Verbindungen zwischen _Kosten_ und _Wert_ existieren (andere Begriffe hierfür sind _Aufwand_ und _Nutzen_).
* Sie können verschiedene betriebswirtschaftlicher Größen nutzen, um mögliche Verbesserungen gegenüber anderen Stakeholdern zu motivieren und zu argumentieren.
    Dabei können sie:
** Zwischen direkten (z.B. für Entwicklung oder Betrieb) und indirekten Kosten (z.B. für Kontextwechsel oder Verzögerungen) von Investitionen für realistischere Schätzungen unterscheiden.
** Langfristige Investitionen in Vermögenswerte (CAPEX) von laufenden Betriebsausgaben für den täglichen Betrieb (OPEX) unterscheiden, um einen passenden Grad an Flexibilität zu erreichen  (siehe <<capexopex>>).
** Bereits genehmigte strategische Initiativen nutzen, um Verbesserungsmaßnahmen an diesen Prioritäten auszurichten und zu verknüpfen.
** Vorgegebene IT-Budgetstrukturen wie 'Plan – Build – Run' für Verbesserungen ausnutzen.
** Grundlegende Argumentationslinien unter Anwendung wirtschaftlicher Konzepte wie ROI, Break-Even-Analyse, Abschreibungen und Amortisation verstehen.
** Geeignete Wege zur Zuordnung von Problem- und Verbesserungskosten auf der Basis von Kostentreibern (intern und extern) finden.
** Potenzielle Kosten im Zusammenhang mit Risiken und technische Schulden identifizieren, einschließlich Auswirkungen auf Projektlaufzeiten und möglicher Schäden am Unternehmensruf.

[[LZ-3-2]]
==== LZ 3-2: Grundbegriffe für Evaluierung/Schätzung

* Begriffe „Schätzung“, „Beobachtung“ und „Messung“ erklären und in der Evaluierung von Problemen und Lösungsansätzen anwenden
* Schätzungen in Intervallen angeben können. Sie kennen verschiedene Ansätze für Intervallschätzungen:
** Konfidenzintervall
** Minimum-Maximum-Intervall
** Worst-/Average-/Best-Case-Schätzung
* Wahrscheinlichkeit der Korrektheit von Schätzungen beurteilen und angeben können (etwa durch Größe von Intervallschätzungen)
* Schätzgegenstände identifizieren und benennen, beispielsweise Arbeitsstunden
* Schätzparameter und Einflussfaktoren auf Schätzungen identifizieren
* Explizite Annahmen treffen, um Schätzparameter in Wertebereichen festlegen zu können.

[[LZ-3-3]]
==== LZ 3-3: Probleme und Lösungsansätze schätzen

Schätzverfahren auf Probleme und Lösungsansätze innerhalb von IT-Systemen und zugehörigen Prozessen anwenden können
// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Argue contextually using business metrics

* Architects understand the connections between _costs_ and _value_ (other terms are _effort_ and _benefit_).
* They know and utilize various business metrics to find the ideal approach for motivating improvements. In doing so, they can:
** Differentiate between direct costs (e.g., for development or operations) and indirect costs (e.g., for context switching or delays) of investments for more realistic estimates.
** Distinguish between long-term investments in assets (CAPEX) and ongoing operating expenses for daily operations (OPEX) to achieve an appropriate level of flexibility (see <<capexopex>>).
** Leverage already approved strategic initiatives to align and connect improvement efforts with these priorities.
** Utilize predefined IT budget structures such as 'Plan – Build – Run' to drive improvements.
** Understand basic lines of argument using economic concepts like ROI, break-even analysis, depreciation, and amortization.
** Find appropriate ways to allocate problem and improvement costs based on cost drivers (internal and external).
** Identify potential costs associated with risks and technical debt, including impacts on project timelines and possible damage to the company's reputation.

[[LG-3-2]]
==== LG 3-2: Basic terms of evaluation and estimation

* Explain the terms “estimation”, “observation”, and “measurement” and apply them to the evaluation of problems and solution approaches.
* Be able to estimate efforts in intervals. Know different approaches for interval estimates:
** Confidence interval,
** Minimum/maximum interval,
** Worst-/Average-/Best-Case estimation.
* Be able to assess and communicate the probability of the correctness of the estimation.
* Identify and name items to be estimated, e.g., hours of work.
* Identify parameters and influencing factors of estimations
* explicit assumption to be able to define estimation parameters in value ranges.

[[LG-3-3]]
==== LG 3-3: Estimate for problems and solution approaches

Apply estimation techniques to problems and solution approaches of IT systems and related processes.
// end::EN[]


