// tag::FEEDBACK[]
:filename: 03-module-block-3/LZ-3-02.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-3-2]]
==== LZ 3-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.
// end::DE[]

// tag::EN[]
[[LG-3-2]]
==== LG 3-2: Know and explain basic terms of evaluation and estimation (R2)

* Explain the terms “estimation“, “observation“ and “measurement“ and apply them to the evaluation of problems and solution approaches.
* Be able to estimate efforts in intervals. Know different approaches for interval estimates:
* Confidence interval,
* Minimum/maximum interval,
* Worst-/Average-/Best-Case estimation.
* Be able to assess and communicate the probability of the correctness of the estimation.
* Identify and name items to be estimated, e. g., hours of work.
* Identify parameters and influencing factors of estimations
* explicit assumption to be able to define estimation parameters in value ranges.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
