// tag::DE[]
[[LZ-3-2]]
==== LZ 3-2: Grundbegriffe für Evaluierung/Schätzung

* Begriffe „Schätzung“, „Beobachtung“ und „Messung“ erklären und in der Evaluierung von Problemen und Lösungsansätzen anwenden
* Schätzungen in Intervallen angeben können. Sie kennen verschiedene Ansätze für Intervallschätzungen:
** Konfidenzintervall
** Minimum-Maximum-Intervall
** Worst-/Average-/Best-Case-Schätzung
* Wahrscheinlichkeit der Korrektheit von Schätzungen beurteilen und angeben können (etwa durch Größe von Intervallschätzungen)
* Schätzgegenstände identifizieren und benennen, beispielsweise Arbeitsstunden
* Schätzparameter und Einflussfaktoren auf Schätzungen identifizieren
* Explizite Annahmen treffen, um Schätzparameter in Wertebereichen festlegen zu können.

// end::DE[]

// tag::EN[]
[[LG-3-2]]
==== LG 3-2: Basic terms of evaluation and estimation

* Explain the terms “estimation“, “observation“ and “measurement“ and apply them to the evaluation of problems and solution approaches.
* Be able to estimate efforts in intervals. Know different approaches for interval estimates:
** Confidence interval,
** Minimum/maximum interval,
** Worst-/Average-/Best-Case estimation.
* Be able to assess and communicate the probability of the correctness of the estimation.
* Identify and name items to be estimated, e. g., hours of work.
* Identify parameters and influencing factors of estimations
* explicit assumption to be able to define estimation parameters in value ranges.

// end::EN[]
