// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Betriebswirtschaftliche Größen

* Kosten und Wert als Begriffspaare erläutern
* Unterschiedliche Arten von betriebswirtschaftlichen Größen benennen und einordnen können, beispielsweise:
** Kosten für direkte Aufwände, Ausbildungskosten, Kapitalkosten (direkte und indirekte Kosten der Investition), Betriebskosten, Opportunitätskosten, Kosten der Verzögerung (Cost of Delay)
** Investitionen und laufenden Kosten, Run-the-Company (RTC) und Develop-the-Company (DTC)
** ROI, Break-Even, Abschreibungen und Amortisierung
** Einmalige und wiederkehrende Aufwände, bekannte und geschätzte Aufwände.

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Economic dimensions

* Explain costs and value as linked concepts.
* Name and classify different kinds of economic dimensions, such as:
** Direct costs, education costs, capital expenditures (direct and indirect cost of investment), operating expenditures, opportunity cost, and cost of delay
** Investment and operating expenses (OPEX), Run-the-Company (RTC) and Develop-the-Company (DTC)
** ROI, break-even, depreciation and amortisation
** One-time and reoccurring costs, known and estimated costs.

// end::EN[]
