// tag::FEEDBACK[]
:filename: 02-module-block-2/LZ-2-05.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-2-5]]
==== LZ 2-5: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.
// end::DE[]

// tag::EN[]
[[LG-2-5]]
==== LG 2-5: Being able to perform a contextual analysis (R1)

* Define and document contextual boundaries: demarcate systems with respect to their technically and logically related neighbours, identify external interfaces.
* Identify connections between external interfaces and stakeholders and use this information for problem analysis.
* Elaborate problems and risks of external interfaces (e. g., via interviews, analysis of known failures, runtime analysis, protocol or log analysis, analysis of organisational dependencies, analysis of quality attributes and/or service levels).

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
