// tag::DE[]
[width=50%]
|===
| Dauer: 60 Min. | Übungszeit: 120 Min.
|===

**Anmerkung**:

=== Begriffe und Konzepte
Innerhalb jeder lizenzierten Schulung muss mindestens ein Beispiel für IMPROVE vorgestellt werden.

Beispiele für Verbesserungsprojekte realer Systeme können durch Trainer und Schulungsanbieter individuell ausgesucht werden und werden seitens iSAQB nicht vorgegeben.

Aufgrund der bei realen IT-Systemen oftmals geltenden Geheimhaltungs- oder Vertraulichkeitsregelungen stellt der iSAQB e. V. Schulungsanbietern und Trainern frei, Beispiele abstrahiert oder nur auszugsweise in Schulungen zu zeigen.

// end::DE[]


// tag::EN[]
[width=50%]
|===
| Duration: 60 min | Practice time: 120 min
|===



=== Terms and concepts
At least one example of IMPROVE must be presented within each licensed course.

Examples for improvement projects of real systems can be individually selected by trainers and training providers and are not specified by iSAQB.

Due to the secrecy or confidentiality regulations that often apply to real IT systems, iSAQB e. V. allows training providers and trainers to show examples in abstract or only in extracts in training courses.

// end::EN[]
