// tag::FEEDBACK[]
:filename: 06-module-block-6.adoc/LZ-6-01.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Dies ist das erste Lernziel in Kapitel 6, lorem ipsum sit dolor

- Was sollen die Teilnehmer können?
   * Fähigkeit 1
   * Fähigkeit 2
   * Fähigkeit 3
   * etc.
- Was sollen die Teilnehmer verstehen?
  * Aussage 1
  * Behauptung 2
  * Erfahrung 3
  * Zusammenhang 4
  * etc.
- Was sollen die Teilnehmer kennen?
  * Zusammenhang Nr. 1
  * Norm Nr. 2
  * Buch Nr. 3
  * etc.

// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Know and understand examples of problems/risks in IT systems (R2)

* Participants should be able to identify and understand the problems and risks of at least one example of a mid- or large-size IT system. Therefore, the trainings should at least describe the system’s main functional and non-functional requirements, quality goals, usage and change scenarios, essential implementation structures as well as important cross-cutting concepts.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
