// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Teilnehmende lernen hier, Softwaresysteme und -architekturen anhand ökonomischer und technischer Ziele systematisch und methodisch zu verbessern. 
Dazu vermitteln entsprechende Schulungen die systematische Trennung von Problemen und Lösungsansätzen, das Erarbeiten von kurz-/mittel- und langfristigen Lösungsstrategien sowie deren Abgleich mit betriebswirtschaftlichen Zielen und Größen.
Zusätzlich zeigt der IMPROVE-Lehrplan typische Ansätze für Verbesserungen auf, beispielsweise Restrukturierungen und Refactoring, Verbesserungen der Analysierbarkeit, Prozessverbesserung, Verbesserung an technischer Infrastruktur, Verbesserung von Qualitätseigenschaften, etc.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

Participants learn to methodically improve software systems and architectures, guided by economic and technical goals.
The training imparts the systematic separation of problem and solution, the elaboration of short-, mid- and long-term solution strategies as well as their alignment with business goals and measures.
In addition, the IMPROVE curriculum teaches typical approaches of improvement, e. g., restructuring and refactoring, improving analyzability, process improvement, improvement of technical infrastructure, improvement of quality attributes, etc.

// end::EN[]
