

// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Das Modul präsentiert den Teilnehmerinnen und Teilnehmern {curriculum-name} als …
Am Ende des Moduls kennen die Teilnehmerinnen und Teilnehmer … und können …
// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

Participants learn to methodically improve software systems and architectures, guided by economic and technical goals.
The trainings impart the systematic separation of problem and solution, the elaboration of short-, mid- and long-term solution strategies as well as their alignment with business goals and measures.

In addition, the {curriculum-short} curriculum teaches typical approaches of improvement, e. g., restructuring and refactoring, improving analysability, process improvement, improvement of technical infrastructure, improvement of quality attributes, etc.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Hier bitte das Modul bzw. dessen Lerninhalte zusammenfassend in 5-8 Sätzen beschreiben. Dabei `{curriculum-name}`
nicht entfernen, beim Zusammenbauen wird dieser Platzhalter mit dem Modulnamen ersetzt.
====
// end::REMARK[]
