// tag::DE[]
=== Voraussetzungen für das Modul IMPROVE

Teilnehmende sollten folgende Kenntnisse und/oder Erfahrung mitbringen:

* Praktische Erfahrung in Entwurf und Entwicklung kleiner bis mittelgroßer Softwaresysteme.
* Erste praktische Erfahrung in Wartung oder Weiterentwicklung von Softwaresystemen.
* Erste praktische Erfahrung im Umgang mit bestehendem Quellcode mittlerer oder großer Systeme, insbesondere Analyse, Bewertung, Qualitätsprüfung, Refactoring sowie Anwendung von Metriken.

Hilfreich für das Verständnis einiger Konzepte sind darüber hinaus:

* Kenntnisse und praktische Erfahrung im Refactoring
* Kenntnisse oder erste praktische Erfahrung in Review oder Bewertung von Software:
** Grundkenntnisse in Software-Metriken, z. B. Metriken zur Messung von Kopplung, Kohäsion, Abhängigkeit, Komplexität
** Grundkenntnisse der Laufzeitanalyse von Software, etwa Profiling, Tracing, Log-Analyse, Analyse von Anwendungsdaten
** Grundkenntnisse und erste Erfahrung in der Aufwandsschätzung von Entwicklungsaufgaben
* Erste praktische Erfahrung in der Anforderungsanalyse sowie dem Umgang mit unterschiedlichen Stakeholdern von Entwicklungsprojekten.
* Erste praktische Erfahrung in der Analyse von Entwicklungsprozessen.

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants *should* have the following knowledge and/or experience:

* Hands-on experience in design and development of small to medium size
software systems.
* Some hands-on experience in maintenance and evolution of a software
system.
* Some hands-on experience with the handling of source code of medium to
large scale systems, in particular analysis, assessment, quality check,
refactoring, and applying of metrics.

Furthermore, the following will be useful for understanding certain
concepts:

* Knowledge and hands-on experience with refactoring (see e. g.,
[Fowler+99])
* Knowledge or some hands-on experience with review and evaluation of
software:
** Basic knowledge about software metrics, such as metrics to measure
coupling, cohesion, dependency and complexity.
** Basic knowledge of software run time analysis such as profiling,
tracing, log analysis and analysis of application data.
** Basic knowledge and some experience with the estimation of
development efforts.
* Some hands-on experience with requirements engineering as well as
contact with various stakeholders in development projects.
* Some hands-on experience with analysis of development processes.

// end::EN[]
