
// tag::DE[]
=== Ergänzende Informationen, Begriffe, Übersetzungen

Soweit für das Verständnis des Lehrplans erforderlich, haben wir Fachbegriffe ins https://github.com/isaqb-org/glossary[iSAQB-Glossar] aufgenommen, definiert und bei Bedarf durch die Übersetzungen der Originalliteratur ergänzt.

=== Helfen Sie uns, diesen Lehrplan zu verbessern

Sie finden die neueste Version dieses Dokuments online (https://isaqb-org.github.io/curriculum-improve/), wo Sie gerne Feedback und Verbesserungsvorschläge geben können.
// end::DE[]

// tag::EN[]
=== Further information, terminology, translations

To the extent necessary for understanding the curriculum, we have added definitions of technical terms to the https://github.com/isaqb-org/glossary[iSAQB glossary] and complemented them by references to (translated) literature.

[discrete]
=== Help us improve this curriculum

You find the most recent version of this document online (https://isaqb-org.github.io/curriculum-improve/), where you are encouraged to provide feedback.
// end::EN[]
