// header file for curriculum section "References"
// (c) iSAQB e.V. (https://isaqb.org)
// ===============================================


[bibliography]
== {references}


// tag::DE[]
Dieser Abschnitt enthält Literaturhinweise, auf deren Basis das Curriculum teilweise entstanden ist.
// end::DE[]

// tag::EN[]
This section contains references on which the curriculum is partly based on.
// end::EN[]


A +

Architecture Improvement Method – Open-Source collection of practices and patterns to support software evolution, modernization, maintenance, migration and improvement of software systems. https://aim42.org/[https://aim42.org] as well as https://aim42.github.io/[https://aim42.github.io]


B +

Len Bass, Paul Clements, Rick Kazman: Software Architecture in Practice. 3rd Edition, Addison-Wesley, 2012.


C +

Paul Clements, Rick Kazman, Mark Klein: Evaluating Software Architectures Methods and Case Studies. Addison-Wesley, 2001.


F +

Michael Feathers: Working Effectively with Legacy Code. Prentice Hall, 2007.

Martin Fowler, Kent Beck: Refactoring: Improving the Design of Existing Code. Addison-Wesley, 1999.


L +

Martin Lippert, Stefan Roock: Refactoring in Large Software Projects: Performing Complex Restructurings Successfully. Wiley, 2007.

Carola Lilienthal: Sustainable Software Architecture: Analyze and Reduce Technical Debt. dpunkt.verlag, 2019.


M +

Steve McConnell: Software Estimation: Demystifying the Black Art. Microsoft Press, 2006.

Stephan Murer, Bruno Bonati: Managed Evolution: A Strategy for Very Large Information Systems. Springer, 2010.

N +

Sam Newman: Monolith to Microservices: Evolutionary Patterns to Transform Your Monolith. O'Reilly, 2019.
