// tag::FEEDBACK[]
:filename: 05-module-block-5/01-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: XXX Min. | Übungszeit: XXX Min.
|===

=== Begriffe und Konzepte
* Begriff 1
* Begriff 2
* Begriff 3

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 360 min | Exercises: 0 min
|===

=== Terms and concepts
* Structural vs. conceptual improvement
* Process and product improvement
* Improvement of code, data, cross-cutting concepts, processes, infrastructure, analysability/monitoring
* Reduction of technical debts
* Ways to improve source code
** Refactoring
** Reduction of complexity and coupling
** Improve readability and comprehensibility
* Process automation to lower risk of changes, in particular, automated tests. 

Note 1: The following learning goals should only give indications for typical improvements. In concrete systems or scenarios other approaches may be necessary that cannot be anticipated in this curriculum.

Note 2: In this chapter trainings should present detailed technical approaches for possible improvements.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
