// tag::FEEDBACK[]
:filename: 05-module-block-5/LZ-5-02.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-5-2]]
==== LZ 5-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.
// end::DE[]

// tag::EN[]
[[LG-5-2]]
==== LG 5-2: Know and being able to apply improvement measures for source code (R1)

* Know and being able to apply typical technology/programming language
specific refactorings (semantics preserving simplification measures in source code). Trainings should conduct exercises if required.
* Better use of technology or use better technology (change of technology).
* Explain the connection between technical debts and refactoring.
* Know and be able to apply measures and patterns to reduce coupling at source code level.
* Know and be able to apply measures and patterns to make source code more comprehensible, e. g., Clean-Code principles.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
