// tag::FEEDBACK[]
:filename: 05-module-block-5/LZ-5-03.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-5-3]]
==== LZ 5-3: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.
// end::DE[]

// tag::EN[]
[[LG-5-3]]
==== LG 5-3: Know and be able to apply possible approaches for automated testing to reduce risks of change (R2)

* Know and being able to autonomously apply automated tests (unit-,
integration-, acceptance-, regression-tests) as a means of early
detection of defects in change or improvement projects. (Trainings
should provide exercises if required.)
* Being able to autonomously identify adequate locations/interfaces/components where the introduction of automated tests will be suitable for specific change scenarios.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
