// tag::DE[]
=== {learning-goals}
[[LZ-1-01]]
==== LZ 1-01: Identifizieren und bewerten von Änderungstreibern in Softwaresystemen

* Funktionale Erweiterung oder Änderung
* Änderung von Qualitätsanforderungen oder -zielen
* Änderungen in technischem oder fachlichen Kontext (z. B. Änderung an externen Schnittstellen)
* Fehlerbehebung
* Organisatorische Änderungen (z. B. Änderungen juristischer Rahmenbedingungen oder Anforderungen, an Organisationsstrukturen in Fachbereichen, Entwicklung oder Betrieb)
* Kosten- oder Aufwandsreduktion, insbesondere bezüglich
** Entwicklungskosten oder -aufwände
** Betriebskosten oder -aufwände
** Kosten der Fehlerbehebung und Kosten von Folgeschäden
** Kosten beteiligter Prozesse
** Opportunitätskosten
* Intrinsische Motivation beteiligter Personen, insbesondere Softwareentwickler:innen und -architekt:innen
* Aktualisierung verwendeter Technologien, etwa Betriebssysteme, Middleware, Bibliotheken, Frameworks, Hardware oder ähnliche.

[[LZ-1-02]]
==== LZ 1-02: Erkennen und klassifizieren technischer und organisatorischer Defizite

Softwarearchitekt:innen sollten verschiedene Arten von technischen und organisatorischen Defiziten (_Schulden_) erkennen (siehe <<LZ-2-02>>) und benennen können, beispielsweise:

* Konzeptionelle Schwächen, beispielsweise Verletzung konzeptioneller Integrität, übermässige Redundanz
* Strukturelle Probleme in Daten oder Datenstrukturen
* Strukturelle Probleme im Quellcode, etwa:
** fehlende oder unzureichende Modularisierung,
** enge Kopplung,
** hohe Komplexität,
** geringe Kohäsion,
** handwerkliche Schwächen in der Programmierung, etwa nicht-idiomatische Verwendung von Programmiersprachen oder –werkzeugen,
* Probleme mit Anwendungsdaten, Datenstrukturen oder Datenspeicherung
* Laufzeitprobleme in Systemen, etwa Instabilität, mangelnde Robustheit oder Zuverlässigkeit, mangelnde Performance oder zu hoher Ressourcenbedarf, mangelnde Skalierbarkeit
* Probleme bei Erreichung von Qualitätsanforderungen, etwa mangelnde Änderbarkeit, Verständlichkeit, Flexibilität, Sicherheit, Testbarkeit, Portabilität oder andere für das jeweilige System oder Umfeld relevante Qualitätseigenschaften (siehe etwa <<iso25010>> oder <<Q42>>),
* Technische Schwächen: Verwendung nicht angemessener Technologien, falsche Verwendung von Technologien,
* Probleme oder hohe Risiken im Bereich Sicherheit (Datensicherheit, Vertraulichkeit, Zugangsschutz oä),
* Probleme in Arbeitsprozessen oder -abläufen rund um Systeme, beispielsweise:
** Probleme mit Tests, Testvorgehen, Testdaten, Testausführung, Testumgebungen,
** Probleme mit Freigabe/Release, Deployment, Betrieb, Monitoring/Alerting,
** Probleme aufgrund von fehlendem Wissen, fehlender oder mangelhafter Dokumentation,
** Probleme in Kommunikation mit/zwischen Stakeholdern


[[LZ-1-03]]
==== LZ 1-03: Differenzieren zwischen Problemen, Ursachen und Lösungsansätzen

Kernbegriffe von Evolution und Änderung von Software:

* Problem (Issue)
* Lösungsansatz (Opportunity for Improvement)
* Kosten (von Problemen, Lösungsansätzen, Maßnahmen)
* Ursachen (Root cause) versus Symptom
* Risiko

[[LZ-1-04]]
==== LZ 1-04: Differenzieren möglicher Verbesserungsstrategien für IT-Systeme

Beispielsweise:

* Ad-hoc Verbesserung, einmalige Verbesserung
* Schrittweise Verbesserung (mittel- bis langfristig angelegt)
* Verbesserung durch Neuentwicklung (Rewrite) eines Systems oder Teilen davon
* Rein strukturelle Verbesserungen (Refactoring)
* Konzeptionelle/strukturelle Verbesserung (Re-Architecting, Reengineering)
// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-1-01]]
==== LG 1-01: Identify and evaluate drivers for software changes

* Extending and changing features
* Change in quality requirements and goals
* Changes in technical or business context (e.g., change in external interfaces)
* Bug fixing
* Changes in organization (e.g., changes of legal conditions or requirements, organizational structure of business units, development or operations)
* Reduce of costs or efforts, especially with respect to:
** Costs or efforts of development
** Costs or efforts of operations
** Costs of bug fixing and consequential damage
** Costs of involved processes
** Opportunity costs
* Intrinsic motivation of stakeholders, especially software developers and architects.
* Update of applied technology such as operating systems, middleware, libraries, frameworks, hardware or similar.

[[LG-1-02]]
==== LG 1-02: Recognize and classify technical and organizational deficits

Software architects should be able to recognize and identify various types of technical and organizational deficits (_debts_) (see <<LG-2-2>>), for example:

* Conceptual weaknesses, such as violation of conceptual integrity, excessive redundancy
* Structural problems in data or data structures
* Structural problems in the source code, such as:
** missing or insufficient modularization,
** tight coupling,
** high complexity,
** low cohesion,
** technical weaknesses in programming, such as non-idiomatic use of programming languages or tools
* Problems with application data, data structures, or data storage
* Runtime problems in systems, such as instability, lack of robustness or reliability, poor performance or excessive resource requirements, lack of scalability
* Problems in meeting quality requirements, such as lack of changeability, comprehensibility, flexibility, security, testability, portability, or other quality characteristics relevant to the respective system or environment (see, for example, <<iso25010>> or <<Q42>>)
* Technical weaknesses: use of inappropriate technologies, incorrect use of technologies
* Problems or high risks in the area of security (data security, confidentiality, access protection, etc.)
* Problems in work processes or procedures related to systems, for example:
** Problems with tests, test procedures, test data, test execution, test environments
** Problems with approval/release, deployment, operation, monitoring/alerting
** Problems due to lack of knowledge, missing or inadequate documentation
** Problems in communication with/between stakeholders


[[LG-1-03]]
==== LG 1-03: Differentiate between problems, root causes, and solutions

Core terms of software evolution and change:

* Problem (issue)
* Solution approach (opportunity for improvement)
* Costs (of problems, solution approaches, measures)
* Root cause versus symptom
* Risk

[[LG-1-04]]
==== LG 1-04: Differentiate types of improvement strategies for IT systems

For example:

* Ad-hoc improvement, one-off improvement
* Stepwise improvement (mid- to long-term)
* Improvement by newly developed system or system parts (rewrite)
* Purely structural improvements (refactoring)
* Conceptual/structural improvements (re-architecting, reengineering)
// end::EN[]


