// tag::DE[]
=== {learning-goals}
[[LZ-1-01]]
==== LZ 1-01: Identifizieren und Bewerten von Änderungstreibern in Softwaresystemen

* Funktionale Erweiterung oder Änderung
* Änderung von Qualitätsanforderungen oder -zielen
* Änderungen in technischem oder fachlichem Umfeld
* Fehlerbehebung
* Organisatorische Änderungen
* Kosten- oder Aufwandsreduktion
* Aktualisierung verwendeter Technologien

[[LZ-1-02]]
==== LZ 1-02: Erkennen und Klassifizieren technischer und organisatorischer Defizite

Softwarearchitekt:innen sollten verschiedene Arten von technischen und organisatorischen Defiziten (_Schulden_) erkennen (siehe <<LZ-2-02>>) und benennen können, beispielsweise:

* Konzeptionelle Schwächen der Architektur und des Designs
* Strukturelle Probleme in Daten, Datenstrukturen und Quellcode
* Probleme bei der Erreichung von Qualitätsanforderungen
* Nicht angemessene oder falsche Verwendung von Technologien
* Probleme in Arbeitsprozessen oder -abläufen rund um die Entwicklung eines Systems

[[LZ-1-03]]
==== LZ 1-03: Definieren und Unterscheiden von Problem, Symptom, Ursache, Risiko und Lösung

Softwarearchitekt:innen können Grundbegriffe von Softwareevolution, -änderung und -verbesserung differenzieren und erklären, beispielsweise:

* Problem, Lösungsansätze, Maßnahmen
* Kosten von Problemen, Konsequenzen von Lösungsansätzen, Nutzen von Maßnahmen
* Ursachen (Root cause) versus Symptom
* Risiko und technische Schulden

Siehe <<kruchtenTechDebt>>.

// end::DE[]


// tag::EN[]
=== {learning-goals}

[[LG-1-01]]
==== LG 1-01: Identify and evaluate drivers for software changes

* Extending and changing features
* Change in quality requirements and goals
* Changes in technical or business context (e.g., change in external interfaces)
* Bug fixing
* Changes in organization (e.g., changes of legal conditions or requirements, organizational structure of business units, development or operations)
* Reduction of costs or efforts, especially with respect to:
** Costs or efforts of development
** Costs or efforts of operations
** Costs of bug fixing and consequential damage
** Costs of involved processes
** Opportunity costs
* Intrinsic motivation of involved persons, especially software developers and architects.
* Update of applied technologies such as operating systems, middleware, libraries, frameworks, hardware or similar.

[[LG-1-02]]
==== LG 1-02: Recognize and classify technical and organizational deficits

Software architects should be able to recognize and identify various types of technical and organizational deficits (_debts_) (see <<LG-2-02>>), for example:

* Conceptual weaknesses, such as violation of conceptual integrity, excessive redundancy
* Structural problems in data or data structures
* Structural problems in the source code, such as:
** missing or insufficient modularization,
** tight coupling,
** high complexity,
** low cohesion,
** weaknesses in programming, such as non-idiomatic use of programming languages or tools
* Problems with application data, data structures, or data storage
* Runtime problems in systems, such as instability, lack of robustness or reliability, poor performance or excessive resource requirements, lack of scalability
* Problems in meeting quality requirements, such as lack of changeability, comprehensibility, flexibility, security, testability, portability, or other quality characteristics relevant to the respective system or environment (see, for example, <<iso25010>> or <<Q42>>)
* Technical weaknesses: use of inappropriate technologies, incorrect use of technologies
* Problems or high risks in the area of security (data security, confidentiality, access protection, etc.)
* Problems in work processes or procedures related to systems, for example:
** Problems with tests, test procedures, test data, test execution, test environments
** Problems with approval/release, deployment, operation, monitoring/alerting
** Problems due to lack of knowledge, missing or inadequate documentation
** Problems in communication with/between stakeholders
** Continual scope churn under time/cost pressure (frequently changing requirements, priorities, or acceptance criteria), leading to ad-hoc work, erosion of conceptual integrity, and accumulation of legacy/technical debt.

See <<kruchtenTechDebt>>, <<starke-debt>>, <<ernst-techDebt>>.

[[LG-1-03]]
==== LG 1-03: Define and distinguish problem, symptom, root cause, risk and solution

Software architects can explain the concept of "technical and organizational debt" (see <<LG-1-02>>) and, in particular, differentiate it from the concept of debt in economics and finance.
This includes, in particular:

* Understanding that "debt" in the context of IT systems is a metaphor and not a real financial construct. 
* Debt in economics and finance has clearly defined (in some cases legally regulated) mechanisms:
** a predefined quantified amount (i.e., quantified _amount of debt_),
** formalized roles and responsibilities (creditor, debtor),
** agreed interest and repayment plans (i.e., repayment of debt defined in advance)
** formal legal and accounting treatment

Software architects can differentiate and explain additional core terms of software evolution and change, for example:

* Problem (issue)
* Solution approach (opportunity for improvement)
* Costs (of problems, solution approaches, measures)
* Root cause versus symptom
* Risk

These terms are prerequisite for <<LG-2-01>>.

// end::EN[]