=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Gründe für Veränderungen an Software
* Funktionale Erweiterung oder Änderung
* Änderung von Qualitätsanforderungen oder -zielen
* Änderungen in technischem oder fachlichen Kontext (z. B. Änderung an externen Schnittstellen)
* Fehlerbehebung
* Organisatorische Änderungen (z. B. Änderungen juristischer Rahmenbedingungen oder Anforderungen, an Organisationsstrukturen in Fachbereichen, Entwicklung oder Betrieb)
* Kosten- oder Aufwandsreduktion, insbesondere bezüglich
** Entwicklungskosten oder -aufwände
** Betriebskosten oder -aufwände
** Kosten der Fehlerbehebung und Kosten von Folgeschäden
** Kosten beteiligter Prozesse
** Opportunitätskosten
* Intrinsische Motivation beteiligter Personen, insbesondere Software-Entwickler und -Architekten
* Aktualisierung verwendeter Technologien, etwa Betriebssysteme, Middleware, Bibliotheken, Frameworks, Hardware oder ähnliche.

[[LZ-1-2]]
==== LZ 1-2: Typische Kategorien von Problemen an Software

* Konzeptionelle Schwächen, beispielsweise Verletzung konzeptioneller Integrität, Redundanz, Verwendung nicht angemessener Technologien, falsche Verwendung von Technologien
* Strukturelle Probleme in Daten oder Datenstrukturen
* Strukturelle Probleme im Quellcode, etwa:
** fehlende oder unzureichende Modularisierung,
** enge Kopplung,
** hohe Komplexität,
** geringe Kohäsion,
** handwerkliche Schwächen in der Programmierung, etwa nicht-idiomatische Verwendung von Programmiersprachen oder –werkzeugen.
* Laufzeitprobleme in Systemen, etwa Instabilität, mangelnde Robustheit oder Zuverlässigkeit, mangelnde Performance oder zu hoher Ressourcenbedarf, mangelnde Skalierbarkeit, mangelnde Transparenz von Systemabläufen
* „Altlasten“ durch häufige Anforderungsänderung unter Zeit- und/oder Kostendruck
* Verschiedene Arten von technischen Schulden erkennen und benennen
* Probleme bei Erreichung von Qualitätszielen oder -anforderungen, etwa mangelnde Änderbarkeit oder Wartbarkeit, geringe Flexibilität, mangelnde Sicherheit oder mangelnde Portabilität
* Probleme in Entwicklungs- oder Betriebsprozesse oder sonstiger beteiligter Prozesse (z. B. Anforderungsmanagement, Test/QS, Konfiguration, Deployment, Monitoring/Alerting).

[[LZ-1-3]]
==== LZ 1-3: Kernbegriffe für Softwareevolution und -änderung

Kernbegriffe von Evolution und Änderung von Software:

* Problem (Issue)
* Lösungsansatz (Opportunity for Improvement)
* Kosten (von Problemen, Lösungsansätzen, Maßnahmen)
* Ursachen (Root cause) versus Symptom
* Risiko

[[LZ-1-4]]
==== LZ 1-4: Mögliche Vorgehensweisen bei Änderungen

Beispielsweise:

* Ad-hoc Verbesserung, einmalige Verbesserung
* Schrittweise Verbesserung (mittel- bis langfristig angelegt)
* Verbesserung durch Neuentwicklung (Rewrite) eines Systems oder Teilen davon
* Rein strukturelle Verbesserungen (Refactoring)
* Konzeptionelle/strukturelle Verbesserung (Re-Architecting, Reengineering)


// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Reasons for software changes

* Extending and changing features
* Change in quality requirements and goals
* Changes in technical or business context (e.g., change in external interfaces)
* Bug fixing
* Changes in organization (e.g., changes of legal conditions or requirements, organizational structure of business units, development or operations)
* Reduce of costs or efforts, especially with respect to:
** Costs or efforts of development
** Costs or efforts of operations
** Costs of bug fixing and consequential damage
** Costs of involved processes
** Opportunity costs
* Intrinsic motivation of stakeholders, especially software developers and architects.
* Update of applied technology such as operating systems, middleware, libraries, frameworks, hardware or similar.

[[LG-1-2]]
==== LG 1-2: Typical categories of problems in software

* Conceptual weaknesses, e.g., violation of conceptual integrity, redundancy, use of inappropriate technology, incorrect use of technology.
* Structural problems in data or data structures.
* Structural problems in source code, such as:
** Missing or inadequate modularization,
** Tight coupling,
** High complexity,
** Low cohesion,
** Flaws in programming, e.g., non-idiomatic use of languages or tools.
* Runtime problems in systems, like instability, lack of robustness or reliability, insufficient performance or extensive resource demands, insufficient scalability, insufficient transparency of system processes
* “Legacy” gathered by frequent changes of requirements made under time and/or cost pressure.
* Recognize and name different kinds of technical debts.
* Problems to achieve quality goals or requirements, e.g., insufficient changeability or maintainability, low flexibility, insufficient security or lack of portability.
* Problems in development, operations or other involved processes (e.g., requirements management, test/QA, configuration, deployment, monitoring/alerting).

[[LG-1-3]]
==== LG 1-3: Core terms of software evolution and -change

Core terms of software evolution and change:

* Problem (issue)
* Solution approach (opportunity for improvement)
* Costs (of problems, solution approaches, measures)
* Root cause versus symptom
* Risk

[[LG-1-4]]
==== LG 1-4: Possible approaches for changes

For example:

* Ad-hoc improvement, one-off improvement
* Stepwise improvement (mid- to long-term)
* Improvement by newly developed system or system parts (rewrite)
* Purely structural improvements (refactoring)
* Conceptual/structural improvements (re-architecting, reengineering)


// end::EN[]


