=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Gründe für Veränderungen an Software
* Funktionale Erweiterung oder Änderung
* Änderung von Qualitätsanforderungen oder -zielen
* Änderungen in technischem oder fachlichen Kontext (z. B. Änderung an externen Schnittstellen)
* Fehlerbehebung
* Organisatorische Änderungen (z. B. Änderungen juristischer Rahmenbedingungen oder Anforderungen, an Organisationsstrukturen in Fachbereichen, Entwicklung oder Betrieb)
* Kosten- oder Aufwandsreduktion, insbesondere bezüglich
** Entwicklungskosten oder -aufwände
** Betriebskosten oder -aufwände
** Kosten der Fehlerbehebung und Kosten von Folgeschäden
** Kosten beteiligter Prozesse
** Opportunitätskosten
* Intrinsische Motivation beteiligter Personen, insbesondere Software-Entwickler und -Architekten
* Aktualisierung verwendeter Technologien, etwa Betriebssysteme, Middleware, Bibliotheken, Frameworks, Hardware oder ähnliche.

[[LZ-1-2]]
==== LZ 1-2: Typische Kategorien von Problemen an Software

* Konzeptionelle Schwächen, beispielsweise Verletzung konzeptioneller Integrität, Redundanz, Verwendung nicht angemessener Technologien, falsche Verwendung von Technologien
* Strukturelle Probleme in Daten oder Datenstrukturen
* Strukturelle Probleme im Quellcode, etwa:
** fehlende oder unzureichende Modularisierung,
** enge Kopplung,
** hohe Komplexität,
** geringe Kohäsion,
** handwerkliche Schwächen in der Programmierung, etwa nicht-idiomatische Verwendung von Programmiersprachen oder –werkzeugen.
* Laufzeitprobleme in Systemen, etwa Instabilität, mangelnde Robustheit oder Zuverlässigkeit, mangelnde Performance oder zu hoher Ressourcenbedarf, mangelnde Skalierbarkeit, mangelnde Transparenz von Systemabläufen
* „Altlasten“ durch häufige Anforderungsänderung unter Zeit- und/oder Kostendruck
* Verschiedene Arten von technischen Schulden erkennen und benennen
* Probleme bei Erreichung von Qualitätszielen oder -anforderungen, etwa mangelnde Änderbarkeit oder Wartbarkeit, geringe Flexibilität, mangelnde Sicherheit oder mangelnde Portabilität
* Probleme in Entwicklungs- oder Betriebsprozesse oder sonstiger beteiligter Prozesse (z. B. Anforderungsmanagement, Test/QS, Konfiguration, Deployment, Monitoring/Alerting).

[[LZ-1-3]]
==== LZ 1-3: Kernbegriffe für Softwareevolution und -änderung

Kernbegriffe von Evolution und Änderung von Software:

* Problem (Issue)
* Lösungsansatz (Opportunity for Improvement)
* Kosten (von Problemen, Lösungsansätzen, Maßnahmen)
* Ursachen (Root cause) versus Symptom
* Risiko

[[LZ-1-4]]
==== LZ 1-4: Mögliche Vorgehensweisen bei Änderungen

Beispielsweise:

* Ad-hoc Verbesserung, einmalige Verbesserung
* Schrittweise Verbesserung (mittel- bis langfristig angelegt)
* Verbesserung durch Neuentwicklung (Rewrite) eines Systems oder Teilen davon
* Rein strukturelle Verbesserungen (Refactoring)
* Konzeptionelle/strukturelle Verbesserung (Re-Architecting, Reengineering)


// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Reasons for software changes

* Extending and changing features as well as bug fixing
* Change in quality requirements and goals
* Changes in technical or business context (e.g., changes in technologies, external interfaces as well as business models)
* Changes in organization (e.g., changes of legal conditions or requirements, organizational structure of business units, development or operations)
* Reducing costs or efforts for development and operations
* Increased intrinsic motivation of stakeholders like software developers and architects.


[[LG-1-2]]
==== LG 1-2: Typical categories of problems in software

* Conceptual weaknesses, e.g., violation of conceptual integrity, redundancy, use of inappropriate technology, incorrect use of technology.
* Structural problems in data or data structures.
* Structural problems in source code.
* Runtime problems in systems.
* “Legacy” gathered by frequent changes of requirements made under time and/or cost pressure.
* Problems to achieve quality goals or requirements.
* Problems in development, operations or other involved processes.


[[LG-1-3]]
==== LG 1-3: Core terms of software evolution and change

Core terms for describing the need for software evolution and change:

* Problem (issue)
* Solution approach (opportunity for improvement)
* Costs of problems, solution approaches / measures
* Root cause, intermediate cause, problem symptom
* Different kinds of risks and technical debts


[[LG-1-4]]
==== LG 1-4: Possible approaches for changes

* Continuous, on-the-spot improvements (e.g., through refactoring)
* Stepwise improvements (e.g., medium- to long-term replacements incl. sunsetting)
* Structural and conceptual improvements at various levels (e.g., reengineering, rearchitecting)
* Major enhancements via newly developed systems or components (e.g., rewrites)
* Changes on the operational level (e.g., rehost, replatform)
* Special cases for changes (e.g., transpilation, archiving, emulation)


// end::EN[]


