// tag::DE[]

[[LZ-1-2]]
==== LZ 1-2: Typische Kategorien von Problemen an Software

*	Konzeptionelle Schwächen, beispielsweise Verletzung konzeptioneller Integrität, Redundanz, Verwendung nicht angemessener Technologien, falsche Verwendung von Technologien
*	Strukturelle Probleme in Daten oder Datenstrukturen
*	Strukturelle Probleme im Quellcode, etwa: 
**	fehlende oder unzureichende Modularisierung,
**	enge Kopplung, 
**	hohe Komplexität, 
**	geringe Kohäsion, 
**	handwerkliche Schwächen in der Programmierung, etwa nicht-idiomatische Verwendung von Programmiersprachen oder –werkzeugen.
*	Laufzeitprobleme in Systemen, etwa Instabilität, mangelnde Robustheit oder Zuverlässigkeit, mangelnde Performance oder zu hoher Ressourcenbedarf, mangelnde Skalierbarkeit, mangelnde Transparenz von Systemabläufen
*	„Altlasten“ durch häufige Anforderungsänderung unter Zeit- und/oder Kostendruck
*	Verschiedene Arten von technischen Schulden erkennen und benennen
*	Probleme bei Erreichung von Qualitätszielen oder -anforderungen, etwa mangelnde Änderbarkeit oder Wartbarkeit, geringe Flexibilität, mangelnde Sicherheit oder mangelnde Portabilität
*	Probleme in Entwicklungs- oder Betriebsprozesse oder sonstiger beteiligter Prozesse (z. B. Anforderungsmanagement, Test/QS, Konfiguration, Deployment, Monitoring/Alerting).


// end::DE[]

// tag::EN[]
[[LG-1-2]]
==== LG 1-2: Typical categories of problems in software

* Conceptual weaknesses, e. g., violation of conceptual integrity, redundancy, use of inappropriate technology, incorrect use of technology.
* Structural problems in data or data structures.
* Structural problems in source code, such as:
** Missing or inadequate modularisation,
** Tight coupling,
** High complexity,
** Low cohesion,
** Flaws in programming, e. g., non-idiomatic use of languages or tools.
* Runtime problems in systems, like instability, lack of robustness or reliability, insufficient performance or extensive resource demands, insufficient scalability, insufficient transparency of system processes
* “Legacy” gathered by frequent changes of requirements made under time and/or cost pressure.
* Recognize and name different kinds of technical debts.
* Problems to achieve quality goals or requirements, e. g., insufficient changeability or maintainability, low flexibility, insufficient security or lack of portability.
* Problems in development, operations or other involved processes (e. g., requirements management, test/QA, configuration, deployment, monitoring/alerting).

// end::EN[]
